import { Case } from "@/types/case";
import { Client } from "@/types/client";
import { Invoice } from "@/types/invoice";
import { Meeting } from "@/types/meeting";
import { Document } from "@/types/document";
import { Task } from "@/types/task";
import { Communication } from "@/types/communication";

// ============ User & Firm Data ============
export const user = {
  firstName: "Fernando",
  lastName: "Cruz",
  name: "Fernando Cruz",
  role: "ATTORNEY",
  email: "fernando.cruz@lawfirm.com",
  phone: "+1 (555) 123-9876",
  avatar:
    "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
};

export const firm = {
  id: "firm_123",
  name: "LawFirm Professional Corporation",
  address: "200 Legal Avenue, Suite 500, New York, NY 10001",
  phone: "+1 (555) 555-5555",
  email: "info@lawfirm.com",
  website: "www.lawfirm.com",
  taxId: "XX-XXXXXXX",
};

export const companyData = {
  id: "company_456",
  name: "TechCorp Inc.",
  logo: "https://techcorp.com/logo.png",
  description:
    "TechCorp is a leading technology company specializing in innovative software solutions and cloud infrastructure.",
  shortDescription: "Leading technology solutions provider.",
  branding: "Process Manager",
  address: "123 Tech Street, Silicon Valley, CA 94025",
  phone: "+1 (555) 123-4567",
  email: "info@techcorp.com",
};

// ============ Clients ============
export const mockClients: Client[] = [
  {
    id: "1",
    firstName: "Robert",
    lastName: "Smith",
    name: "Robert Smith",
    email: "robert@smithent.com",
    phone: "(555) 123-4567",
    company: "Smith Enterprises",
    address: "123 Main St, New York, NY 10001",
    casesCount: 3,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Long-term corporate client specializing in real estate investments with multiple commercial properties.",
    notes: [
      {
        id: "note1",
        content: "Prefers email communication for case updates.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-10-01T09:00:00Z",
        updatedAt: "2024-10-01T09:00:00Z",
        isPrivate: false,
      },
      {
        id: "note2",
        content:
          "Annual retainer agreement expires June 2024 - follow up for renewal.",
        author: "Sarah Paralegal",
        authorId: "para1",
        createdAt: "2024-03-15T14:30:00Z",
        updatedAt: "2024-03-15T14:30:00Z",
        isPrivate: true,
      },
    ],
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2024-10-01T09:00:00Z",
  },
  {
    id: "2",
    firstName: "Sarah",
    lastName: "Williams",
    name: "Sarah Williams",
    email: "sarah.williams@email.com",
    phone: "(555) 234-5678",
    company: "Williams Family Trust",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    casesCount: 2,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Family trust established in 2018, managing estate planning and wealth transfer strategies.",
    notes: [
      {
        id: "note3",
        content: "Meeting scheduled for estate plan review on Nov 20.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2024-10-10T11:15:00Z",
        updatedAt: "2024-10-10T11:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-02-20T14:30:00Z",
    updatedAt: "2024-10-10T11:15:00Z",
  },
  {
    id: "3",
    firstName: "Jennifer",
    lastName: "Lee",
    name: "Jennifer Lee",
    email: "jennifer.lee@email.com",
    phone: "(555) 234-5670",
    company: "",
    address: "606 Birch Lane, Seattle, WA 98101",
    casesCount: 2,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description:
      "Software engineer seeking intellectual property protection for a new mobile application.",
    notes: [
      {
        id: "note4",
        content:
          "Patent filing in progress - needs to provide additional technical specifications.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-09-22T16:45:00Z",
        updatedAt: "2024-09-22T16:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-08-05T09:00:00Z",
    updatedAt: "2024-09-22T16:45:00Z",
  },
  {
    id: "4",
    firstName: "Michael",
    lastName: "Thompson",
    name: "Michael Thompson",
    email: "michael.t@email.com",
    phone: "(555) 456-7890",
    company: "",
    address: "321 Pine St, Houston, TX 77001",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Small business owner seeking assistance with employment contract disputes.",
    notes: [
      {
        id: "note5",
        content: "Former employee settlement negotiations in progress.",
        author: "Richard Labor",
        authorId: "attorney4",
        createdAt: "2024-10-08T09:45:00Z",
        updatedAt: "2024-10-08T09:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-01-10T11:00:00Z",
    updatedAt: "2024-10-08T09:45:00Z",
  },
  {
    id: "5",
    firstName: "Maria",
    lastName: "Garcia",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "(555) 567-8901",
    company: "",
    address: "654 Elm St, Phoenix, AZ 85001",
    casesCount: 1,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description:
      "Personal injury case following motor vehicle accident - settled.",
    notes: [
      {
        id: "note6",
        content: "Case settled. Client satisfied with outcome.",
        author: "Patricia PI",
        authorId: "attorney5",
        createdAt: "2024-12-15T10:45:00Z",
        updatedAt: "2024-12-15T10:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-05-15T13:20:00Z",
    updatedAt: "2024-12-15T10:45:00Z",
  },
  {
    id: "6",
    firstName: "Emily",
    lastName: "Brown",
    name: "Emily Brown",
    email: "emily.brown@email.com",
    phone: "(555) 678-9012",
    company: "",
    address: "789 Maple Dr, Denver, CO 80201",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Commercial property sale documentation and closing.",
    notes: [],
    createdAt: "2024-06-20T09:30:00Z",
    updatedAt: "2024-06-20T09:30:00Z",
  },
  {
    id: "7",
    firstName: "Carlos",
    lastName: "Rodriguez",
    name: "Carlos Rodriguez",
    email: "carlos.rodriguez@email.com",
    phone: "(555) 789-0123",
    company: "",
    address: "1010 Cedar St, Miami, FL 33101",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Criminal defense case for charges of alleged financial fraud.",
    notes: [
      {
        id: "note7",
        content: "Client arraignment completed. Pleaded not guilty.",
        author: "Lisa Defense",
        authorId: "attorney6",
        createdAt: "2024-09-20T09:15:00Z",
        updatedAt: "2024-09-20T09:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-07-01T14:00:00Z",
    updatedAt: "2024-09-20T09:15:00Z",
  },
  {
    id: "8",
    firstName: "James",
    lastName: "Greenwood",
    name: "James Greenwood",
    email: "james.greenwood@email.com",
    phone: "(555) 890-1234",
    company: "Greenwood Holdings",
    address: "1111 Walnut St, Philadelphia, PA 19101",
    casesCount: 2,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Creation of a complex family trust fund with multiple beneficiaries.",
    notes: [],
    createdAt: "2024-03-12T10:15:00Z",
    updatedAt: "2024-03-12T10:15:00Z",
  },
  {
    id: "9",
    firstName: "Alejandro",
    lastName: "Rivera",
    name: "Alejandro Rivera",
    email: "alejandro.rivera@email.com",
    phone: "(555) 901-2345",
    company: "TechVibe Innovations",
    address: "1212 Tech Blvd, Austin, TX 73301",
    casesCount: 1,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description:
      "H-1B visa application for specialized engineer position - initial consultation.",
    notes: [
      {
        id: "note8",
        content: "Initial consultation completed. Client gathering documents.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-12-10T16:30:00Z",
        updatedAt: "2024-12-10T16:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-08-18T16:20:00Z",
    updatedAt: "2024-12-10T16:30:00Z",
  },
  {
    id: "10",
    firstName: "David",
    lastName: "Peterson",
    name: "David Peterson",
    email: "david.peterson@email.com",
    phone: "(555) 012-3456",
    company: "",
    address: "1313 Ash St, Portland, OR 97201",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "International adoption legal proceedings and documentation.",
    notes: [],
    createdAt: "2024-08-08T13:45:00Z",
    updatedAt: "2024-08-08T13:45:00Z",
  },
  {
    id: "11",
    firstName: "Li",
    lastName: "Wei",
    name: "Li Wei",
    email: "li.wei@email.com",
    phone: "(555) 123-4560",
    company: "",
    address: "1414 Pine St, San Francisco, CA 94101",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Defense against deportation proceedings and asylum application.",
    notes: [
      {
        id: "note9",
        content: "Emergency stay granted. Full hearing scheduled.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-10-05T13:15:00Z",
        updatedAt: "2024-10-05T13:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-09-28T11:00:00Z",
    updatedAt: "2024-10-05T13:15:00Z",
  },
  {
    id: "12",
    firstName: "Susan",
    lastName: "Carter",
    name: "Susan Carter",
    email: "susan.carter@email.com",
    phone: "(555) 234-5671",
    company: "",
    address: "1515 Spruce St, Chicago, IL 60601",
    casesCount: 1,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description: "Personal injury lawsuit - settled.",
    notes: [
      {
        id: "note10",
        content: "Case settled for $75,000. Client received payment.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-12-05T11:00:00Z",
        updatedAt: "2024-12-05T11:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-09-10T15:30:00Z",
    updatedAt: "2024-12-05T11:00:00Z",
  },
  {
    id: "13",
    firstName: "Thomas",
    lastName: "Anderson",
    name: "Thomas Anderson",
    email: "thomas.anderson@email.com",
    phone: "(555) 345-6782",
    company: "",
    address: "1616 Birch Ln, Nashville, TN 37201",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Property boundary dispute and nuisance claim against neighbor.",
    notes: [],
    createdAt: "2024-09-15T10:00:00Z",
    updatedAt: "2024-09-15T10:00:00Z",
  },
  {
    id: "14",
    firstName: "Jennifer",
    lastName: "Martin",
    name: "Jennifer Martin",
    email: "jennifer.martin@email.com",
    phone: "(555) 456-7893",
    company: "",
    address: "1717 Willow Way, St. Louis, MO 63101",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Child custody and visitation rights modification case.",
    notes: [
      {
        id: "note11",
        content: "Mediation session scheduled for next week.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-11-01T14:00:00Z",
        updatedAt: "2024-11-01T14:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-08-30T09:45:00Z",
    updatedAt: "2024-11-01T14:00:00Z",
  },
  {
    id: "15",
    firstName: "Robert",
    lastName: "Chen",
    name: "Robert Chen",
    email: "robert.chen@email.com",
    phone: "(555) 567-8904",
    company: "NexTech Startup",
    address: "1818 Innovation Dr, Boston, MA 02101",
    casesCount: 1,
    status: "PROSPECT",
    type: "CORPORATE",
    description:
      "Employee stock option plan and equity distribution legal structuring - initial inquiry.",
    notes: [
      {
        id: "note12",
        content: "Sent engagement letter. Awaiting signature.",
        author: "Corporate Attorney",
        authorId: "attorney9",
        createdAt: "2024-12-01T11:30:00Z",
        updatedAt: "2024-12-01T11:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-10-01T11:30:00Z",
    updatedAt: "2024-12-01T11:30:00Z",
  },
  {
    id: "16",
    firstName: "Amanda",
    lastName: "Johnson",
    name: "Amanda Johnson",
    email: "amanda.johnson@email.com",
    phone: "(555) 678-9015",
    company: "",
    address: "1919 Redwood Blvd, Oakland, CA 94601",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Employment discrimination case against former employer.",
    notes: [
      {
        id: "note13",
        content: "EEOC mediation scheduled for next month.",
        author: "Richard Labor",
        authorId: "attorney4",
        createdAt: "2024-10-17T14:45:00Z",
        updatedAt: "2024-10-17T14:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-09-05T13:15:00Z",
    updatedAt: "2024-10-17T14:45:00Z",
  },
  {
    id: "17",
    firstName: "Brian",
    lastName: "Miller",
    name: "Brian Miller",
    email: "brian.miller@email.com",
    phone: "(555) 789-0126",
    company: "",
    address: "2020 Sequoia Dr, Austin, TX 73301",
    casesCount: 2,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Startup founder requiring assistance with incorporation and investor agreements.",
    notes: [
      {
        id: "note14",
        content: "Series A funding round documentation in preparation.",
        author: "Corporate Attorney",
        authorId: "attorney9",
        createdAt: "2024-10-06T11:15:00Z",
        updatedAt: "2024-10-06T11:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-07-22T10:30:00Z",
    updatedAt: "2024-10-06T11:15:00Z",
  },
  {
    id: "18",
    firstName: "Davis",
    lastName: "Corporation",
    name: "Davis Corporation",
    email: "legal@daviscorp.com",
    phone: "(555) 345-6789",
    company: "Davis Corporation",
    address: "789 Corporate Blvd, Chicago, IL 60601",
    casesCount: 5,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Manufacturing company with international operations, requiring cross-border legal support.",
    notes: [
      {
        id: "note15",
        content: "Merger discussions with German partner ongoing.",
        author: "M&A Specialist",
        authorId: "attorney10",
        createdAt: "2024-10-12T13:00:00Z",
        updatedAt: "2024-10-12T13:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2022-11-05T09:00:00Z",
    updatedAt: "2024-10-12T13:00:00Z",
  },
  {
    id: "19",
    firstName: "TechVantage",
    lastName: "Solutions",
    name: "TechVantage Solutions",
    email: "legal@techvantage.com",
    phone: "(555) 789-0123",
    company: "TechVantage Solutions Inc.",
    address: "101 Tech Park Dr, San Francisco, CA 94101",
    casesCount: 3,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "SaaS company specializing in enterprise software solutions with data privacy concerns.",
    notes: [
      {
        id: "note16",
        content: "GDPR compliance audit scheduled for Q4 2024.",
        author: "Privacy Counsel",
        authorId: "attorney11",
        createdAt: "2024-10-03T10:30:00Z",
        updatedAt: "2024-10-03T10:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-04-18T14:20:00Z",
    updatedAt: "2024-10-03T10:30:00Z",
  },
  {
    id: "20",
    firstName: "Global",
    lastName: "Manufacturing",
    name: "Global Manufacturing Co.",
    email: "compliance@globalmfg.com",
    phone: "(555) 890-1234",
    company: "Global Manufacturing Corporation",
    address: "202 Industrial Way, Detroit, MI 48201",
    casesCount: 4,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Industrial manufacturing firm with complex supply chain and regulatory compliance needs.",
    notes: [
      {
        id: "note17",
        content: "OSHA inspection response required by November 1.",
        author: "Compliance Officer",
        authorId: "attorney12",
        createdAt: "2024-10-18T09:15:00Z",
        updatedAt: "2024-10-18T09:15:00Z",
        isPrivate: true,
      },
    ],
    createdAt: "2023-09-12T11:45:00Z",
    updatedAt: "2024-10-18T09:15:00Z",
  },
  {
    id: "21",
    firstName: "Metro",
    lastName: "Retail",
    name: "Metro Retail Group",
    email: "legal@metrorg.com",
    phone: "(555) 012-3456",
    company: "Metro Retail Group",
    address: "404 Shopping Plaza, Dallas, TX 75201",
    casesCount: 1,
    status: "INACTIVE",
    type: "CORPORATE",
    description:
      "Retail chain with completed merger and acquisition transactions.",
    notes: [
      {
        id: "note18",
        content: "Contract concluded - client acquired by larger competitor.",
        author: "M&A Specialist",
        authorId: "attorney10",
        createdAt: "2024-08-15T11:00:00Z",
        updatedAt: "2024-08-15T11:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2022-06-20T08:30:00Z",
    updatedAt: "2024-08-15T11:00:00Z",
  },
  {
    id: "22",
    firstName: "Quantum",
    lastName: "Financial",
    name: "Quantum Financial",
    email: "compliance@quantumfin.com",
    phone: "(555) 123-4560",
    company: "Quantum Financial Services",
    address: "505 Wall Street, New York, NY 10005",
    casesCount: 6,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Financial services firm with extensive SEC compliance and regulatory reporting needs.",
    notes: [
      {
        id: "note19",
        content: "SEC filing deadline approaching - intensive review required.",
        author: "Securities Attorney",
        authorId: "attorney13",
        createdAt: "2024-10-13T09:30:00Z",
        updatedAt: "2024-10-13T09:30:00Z",
        isPrivate: true,
      },
      {
        id: "note20",
        content: "Quarterly compliance meeting scheduled for October 30.",
        author: "Paralegal Team",
        authorId: "para2",
        createdAt: "2024-10-19T13:00:00Z",
        updatedAt: "2024-10-19T13:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-01-30T16:15:00Z",
    updatedAt: "2024-10-19T13:00:00Z",
  },
  {
    id: "23",
    firstName: "City",
    lastName: "of Springfield",
    name: "City of Springfield",
    email: "cityattorney@springfield.gov",
    phone: "(555) 890-1235",
    company: "Springfield City Government",
    address: "1200 Government Center, Springfield, IL 62701",
    casesCount: 4,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description:
      "Municipal client handling zoning disputes, public contract law, and employment matters.",
    notes: [
      {
        id: "note21",
        content: "Pending zoning case hearing scheduled for December 5.",
        author: "Municipal Attorney",
        authorId: "attorney14",
        createdAt: "2024-10-05T10:00:00Z",
        updatedAt: "2024-10-05T10:00:00Z",
        isPrivate: false,
      },
      {
        id: "note22",
        content: "Annual contract renewal due January 2024.",
        author: "Contracts Manager",
        authorId: "para3",
        createdAt: "2024-09-30T15:20:00Z",
        updatedAt: "2024-09-30T15:20:00Z",
        isPrivate: true,
      },
    ],
    createdAt: "2023-11-10T12:00:00Z",
    updatedAt: "2024-10-05T10:00:00Z",
  },
  {
    id: "24",
    firstName: "State",
    lastName: "Education Department",
    name: "State Education Department",
    email: "legal@education.state.gov",
    phone: "(555) 901-2346",
    company: "State Education Department",
    address: "1300 Capitol Building, Albany, NY 12201",
    casesCount: 3,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description:
      "State agency handling education policy compliance and institutional legal matters.",
    notes: [
      {
        id: "note23",
        content: "Upcoming hearing on special education compliance case.",
        author: "Education Law Specialist",
        authorId: "attorney15",
        createdAt: "2024-10-15T14:00:00Z",
        updatedAt: "2024-10-15T14:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-08-22T09:45:00Z",
    updatedAt: "2024-10-15T14:00:00Z",
  },
  {
    id: "25",
    firstName: "Hope",
    lastName: "Foundation",
    name: "Hope Foundation",
    email: "legal@hopefoundation.org",
    phone: "(555) 345-6781",
    company: "Hope Foundation International",
    address: "1700 Charity Lane, Chicago, IL 60602",
    casesCount: 2,
    status: "PROSPECT",
    type: "NON_PROFIT",
    description:
      "International humanitarian organization - considering legal services for international operations.",
    notes: [
      {
        id: "note24",
        content:
          "Initial meeting scheduled for January. Interested in international compliance.",
        author: "Non-Profit Counsel",
        authorId: "attorney16",
        createdAt: "2024-12-08T11:30:00Z",
        updatedAt: "2024-12-08T11:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-05-05T10:00:00Z",
    updatedAt: "2024-12-08T11:30:00Z",
  },
  {
    id: "26",
    firstName: "Green",
    lastName: "Earth Alliance",
    name: "Green Earth Alliance",
    email: "legal@greenearth.org",
    phone: "(555) 456-7892",
    company: "Green Earth Environmental Alliance",
    address: "1800 Conservation Way, Portland, OR 97202",
    casesCount: 1,
    status: "ACTIVE",
    type: "NON_PROFIT",
    description:
      "Environmental advocacy group focused on conservation and sustainability litigation.",
    notes: [
      {
        id: "note25",
        content:
          "Pending lawsuit against industrial polluter in federal court.",
        author: "Environmental Attorney",
        authorId: "attorney17",
        createdAt: "2024-10-07T13:45:00Z",
        updatedAt: "2024-10-07T13:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-02-14T15:30:00Z",
    updatedAt: "2024-10-07T13:45:00Z",
  },
  // NEW CLIENTS - Adding 14 more to reach 40 total
  {
    id: "27",
    firstName: "Patricia",
    lastName: "O'Connor",
    name: "Patricia O'Connor",
    email: "patricia.oconnor@email.com",
    phone: "(555) 567-8923",
    company: "",
    address: "2121 Harbor View, Boston, MA 02110",
    casesCount: 0,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description:
      "Estate planning consultation requested for blended family situation.",
    notes: [
      {
        id: "note26",
        content:
          "Initial call completed. Will schedule in-person meeting in January.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2024-12-12T10:30:00Z",
        updatedAt: "2024-12-12T10:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-12-12T10:30:00Z",
    updatedAt: "2024-12-12T10:30:00Z",
  },
  {
    id: "28",
    firstName: "Raymond",
    lastName: "Kim",
    name: "Raymond Kim",
    email: "ray.kim@techinnovate.com",
    phone: "(555) 678-9034",
    company: "TechInnovate Solutions",
    address: "2222 Silicon Valley Blvd, San Jose, CA 95101",
    casesCount: 2,
    status: "ACTIVE",
    type: "CORPORATE",
    description: "Patent portfolio management for AI software company.",
    notes: [
      {
        id: "note27",
        content:
          "Filed 3 provisional patents. Preparing non-provisional applications.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-11-20T14:15:00Z",
        updatedAt: "2024-11-20T14:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-09-15T09:00:00Z",
    updatedAt: "2024-11-20T14:15:00Z",
  },
  {
    id: "29",
    firstName: "Elizabeth",
    lastName: "Foster",
    name: "Elizabeth Foster",
    email: "elizabeth.foster@email.com",
    phone: "(555) 789-0145",
    company: "",
    address: "2323 Lake Shore Dr, Chicago, IL 60614",
    casesCount: 0,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description: "Previous client - matter concluded in 2023.",
    notes: [
      {
        id: "note28",
        content: "Real estate closing completed. Client moved out of state.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2023-11-15T13:00:00Z",
        updatedAt: "2023-11-15T13:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-08-10T11:20:00Z",
    updatedAt: "2023-11-15T13:00:00Z",
  },
  {
    id: "30",
    firstName: "Marcus",
    lastName: "Wright",
    name: "Marcus Wright",
    email: "marcus.wright@wrightconsulting.com",
    phone: "(555) 890-1256",
    company: "Wright Consulting Group",
    address: "2424 Business Park Dr, Atlanta, GA 30303",
    casesCount: 1,
    status: "ACTIVE",
    type: "CORPORATE",
    description: "Contract dispute with former business partner.",
    notes: [
      {
        id: "note29",
        content: "Demand letter sent. Awaiting response.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-11-28T09:45:00Z",
        updatedAt: "2024-11-28T09:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-11-15T15:30:00Z",
    updatedAt: "2024-11-28T09:45:00Z",
  },
  {
    id: "31",
    firstName: "Sophia",
    lastName: "Martinez",
    name: "Sophia Martinez",
    email: "sophia.martinez@email.com",
    phone: "(555) 901-2367",
    company: "",
    address: "2525 Rose Ave, Santa Monica, CA 90401",
    casesCount: 1,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description: "Interested in trademark registration for fashion brand.",
    notes: [
      {
        id: "note30",
        content: "Provided fee quote for trademark search. Awaiting decision.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-12-05T11:00:00Z",
        updatedAt: "2024-12-05T11:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-12-01T14:20:00Z",
    updatedAt: "2024-12-05T11:00:00Z",
  },
  {
    id: "32",
    firstName: "Franklin",
    lastName: "Zhang",
    name: "Franklin Zhang",
    email: "frank.zhang@biogenex.com",
    phone: "(555) 012-3478",
    company: "BioGenEx Pharmaceuticals",
    address: "2626 Research Park Dr, San Diego, CA 92121",
    casesCount: 3,
    status: "ACTIVE",
    type: "CORPORATE",
    description: "Patent litigation defense for biologic drug compound.",
    notes: [
      {
        id: "note31",
        content: "Markman hearing scheduled for March.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-11-10T16:20:00Z",
        updatedAt: "2024-11-10T16:20:00Z",
        isPrivate: true,
      },
    ],
    createdAt: "2024-06-20T10:00:00Z",
    updatedAt: "2024-11-10T16:20:00Z",
  },
  {
    id: "33",
    firstName: "Grace",
    lastName: "Park",
    name: "Grace Park",
    email: "grace.park@email.com",
    phone: "(555) 123-4589",
    company: "",
    address: "2727 Cherry Lane, Seattle, WA 98102",
    casesCount: 0,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description: "Former client - immigration matter completed.",
    notes: [
      {
        id: "note32",
        content: "Green card approved. Client no longer needs representation.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-09-30T13:45:00Z",
        updatedAt: "2024-09-30T13:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2023-11-05T09:30:00Z",
    updatedAt: "2024-09-30T13:45:00Z",
  },
  {
    id: "34",
    firstName: "County",
    lastName: "Health Services",
    name: "County Health Services",
    email: "legal@countyhealth.gov",
    phone: "(555) 234-5690",
    company: "County Public Health Department",
    address: "2828 Health Center Dr, Oakland, CA 94612",
    casesCount: 2,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description: "Medical malpractice defense for county hospital system.",
    notes: [
      {
        id: "note33",
        content: "Two active cases in discovery phase.",
        author: "Lisa Defense",
        authorId: "attorney6",
        createdAt: "2024-11-18T11:30:00Z",
        updatedAt: "2024-11-18T11:30:00Z",
        isPrivate: true,
      },
    ],
    createdAt: "2024-08-01T08:45:00Z",
    updatedAt: "2024-11-18T11:30:00Z",
  },
  {
    id: "35",
    firstName: "Rebecca",
    lastName: "Nelson",
    name: "Rebecca Nelson",
    email: "rebecca.nelson@email.com",
    phone: "(555) 345-6701",
    company: "",
    address: "2929 Highland Ave, Denver, CO 80205",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Divorce proceeding with complex asset division.",
    notes: [
      {
        id: "note34",
        content:
          "Financial disclosures submitted. Settlement conference scheduled.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-11-25T15:00:00Z",
        updatedAt: "2024-11-25T15:00:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-10-10T12:15:00Z",
    updatedAt: "2024-11-25T15:00:00Z",
  },
  {
    id: "36",
    firstName: "Andre",
    lastName: "Fontaine",
    name: "Andre Fontaine",
    email: "andre.fontaine@vintagelux.com",
    phone: "(555) 456-7812",
    company: "Vintage Luxury Imports",
    address: "3030 Commerce St, New Orleans, LA 70116",
    casesCount: 1,
    status: "PROSPECT",
    type: "CORPORATE",
    description: "International trade compliance and customs issues.",
    notes: [
      {
        id: "note35",
        content: "Initial consultation scheduled for January.",
        author: "M&A Specialist",
        authorId: "attorney10",
        createdAt: "2024-12-09T10:15:00Z",
        updatedAt: "2024-12-09T10:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-12-09T10:15:00Z",
    updatedAt: "2024-12-09T10:15:00Z",
  },
  {
    id: "37",
    firstName: "Harold",
    lastName: "Jenkins",
    name: "Harold Jenkins",
    email: "harold.jenkins@email.com",
    phone: "(555) 567-8923",
    company: "",
    address: "3131 Maple Ave, Pittsburgh, PA 15201",
    casesCount: 0,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description: "Will and trust documents completed in 2022.",
    notes: [
      {
        id: "note36",
        content: "Estate plan complete. No further action needed.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2022-12-15T14:30:00Z",
        updatedAt: "2022-12-15T14:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2022-11-01T11:00:00Z",
    updatedAt: "2022-12-15T14:30:00Z",
  },
  {
    id: "38",
    firstName: "Community",
    lastName: "Food Bank",
    name: "Community Food Bank",
    email: "legal@communityfoodbank.org",
    phone: "(555) 678-9034",
    company: "Community Food Bank of Ohio",
    address: "3232 Distribution Way, Columbus, OH 43215",
    casesCount: 1,
    status: "ACTIVE",
    type: "NON_PROFIT",
    description: "501(c)(3) compliance and employment law matters.",
    notes: [
      {
        id: "note37",
        content: "Employment handbook review completed.",
        author: "Richard Labor",
        authorId: "attorney4",
        createdAt: "2024-11-22T13:45:00Z",
        updatedAt: "2024-11-22T13:45:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-10-20T09:00:00Z",
    updatedAt: "2024-11-22T13:45:00Z",
  },
  {
    id: "39",
    firstName: "Victoria",
    lastName: "Wong",
    name: "Victoria Wong",
    email: "victoria.wong@email.com",
    phone: "(555) 789-0145",
    company: "",
    address: "3333 Pacific Heights, San Francisco, CA 94109",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Elder law and Medicaid planning for parent.",
    notes: [
      {
        id: "note38",
        content: "Medicaid application submitted. Awaiting determination.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2024-11-30T10:30:00Z",
        updatedAt: "2024-11-30T10:30:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-11-01T14:15:00Z",
    updatedAt: "2024-11-30T10:30:00Z",
  },
  {
    id: "40",
    firstName: "Steven",
    lastName: "Caldwell",
    name: "Steven Caldwell",
    email: "steven.caldwell@caldwellrealty.com",
    phone: "(555) 890-1256",
    company: "Caldwell Realty Group",
    address: "3434 Commercial Ave, Dallas, TX 75202",
    casesCount: 2,
    status: "ACTIVE",
    type: "CORPORATE",
    description: "Commercial lease disputes and property acquisitions.",
    notes: [
      {
        id: "note39",
        content:
          "Successfully negotiated lease modification for downtown property.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-12-02T16:15:00Z",
        updatedAt: "2024-12-02T16:15:00Z",
        isPrivate: false,
      },
    ],
    createdAt: "2024-07-15T08:30:00Z",
    updatedAt: "2024-12-02T16:15:00Z",
  },
];

// ============ Cases ============
export const mockCases: Case[] = [
  {
    id: "1",
    title: "Smith vs. Johnson Corp",
    clientId: "1",
    client: "Robert Smith",
    status: "ACTIVE",
    practiceArea: "CIVIL_LITIGATION",
    priority: "HIGH",
    openedAt: "2024-08-15",
    nextDeadline: "2024-12-28",
    description:
      "Civil litigation case involving breach of contract dispute with Johnson Corporation.",
    notes: [
      {
        id: "n1",
        content:
          "Initial consultation completed. Client provided all relevant documents.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-08-15T10:00:00Z",
        updatedAt: "2024-08-15T10:00:00Z",
        isPrivate: false,
      },
      {
        id: "n2",
        content: "Filed initial complaint with the court.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-08-20T14:30:00Z",
        updatedAt: "2024-08-20T14:30:00Z",
        isPrivate: false,
      },
      {
        id: "n3",
        content:
          "Discovery phase ongoing. Opposing counsel requested extension.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-10-15T11:20:00Z",
        updatedAt: "2024-10-15T11:20:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "2",
    title: "Williams Family Trust Establishment",
    clientId: "2",
    client: "Sarah Williams",
    status: "CLOSED",
    practiceArea: "ESTATE_PLANNING",
    priority: "MEDIUM",
    openedAt: "2024-09-01",
    nextDeadline: "2024-12-30",
    description:
      "Estate planning and will preparation for the Williams family - completed.",
    notes: [
      {
        id: "n4",
        content: "Trust documents finalized and executed. Case closed.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2024-12-10T13:15:00Z",
        updatedAt: "2024-12-10T13:15:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "3",
    title: "Davis Corp Merger",
    clientId: "18",
    client: "Davis Corporation",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-07-10",
    nextDeadline: "2025-01-15",
    description:
      "Handling merger and acquisition documentation for Davis Corporation.",
    notes: [
      {
        id: "n5",
        content: "Due diligence phase 1 completed. Phase 2 initiated.",
        author: "M&A Specialist",
        authorId: "attorney10",
        createdAt: "2024-08-05T09:30:00Z",
        updatedAt: "2024-08-05T09:30:00Z",
        isPrivate: false,
      },
      {
        id: "n6",
        content: "German counterparty submitted additional document requests.",
        author: "M&A Specialist",
        authorId: "attorney10",
        createdAt: "2024-10-20T16:45:00Z",
        updatedAt: "2024-10-20T16:45:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "4",
    title: "Thompson Divorce",
    clientId: "4",
    client: "Michael Thompson",
    status: "ARCHIVED",
    practiceArea: "FAMILY_LAW",
    priority: "LOW",
    openedAt: "2024-03-20",
    nextDeadline: "2024-11-30",
    description:
      "Divorce proceedings and asset division - finalized and archived.",
    notes: [
      {
        id: "n7",
        content: "Settlement agreement finalized. Case archived.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-12-01T10:30:00Z",
        updatedAt: "2024-12-01T10:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "5",
    title: "Garcia Immigration",
    clientId: "5",
    client: "Maria Garcia",
    status: "ACTIVE",
    practiceArea: "IMMIGRATION",
    priority: "MEDIUM",
    openedAt: "2024-10-05",
    nextDeadline: "2025-02-20",
    description: "Immigration visa application and documentation.",
    notes: [
      {
        id: "n8",
        content: "Form I-130 petition filed. Receipt notice received.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-10-15T14:20:00Z",
        updatedAt: "2024-10-15T14:20:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "6",
    title: "Brown Property Sale",
    clientId: "6",
    client: "Emily Brown",
    status: "CLOSED",
    practiceArea: "REAL_ESTATE",
    priority: "MEDIUM",
    openedAt: "2024-11-01",
    nextDeadline: "2025-01-10",
    description: "Commercial property sale - closed successfully.",
    notes: [
      {
        id: "n9",
        content: "Closing completed. Deed recorded.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2025-01-10T16:30:00Z",
        updatedAt: "2025-01-10T16:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "7",
    title: "State vs. Rodriguez",
    clientId: "7",
    client: "Carlos Rodriguez",
    status: "ACTIVE",
    practiceArea: "CRIMINAL_DEFENSE",
    priority: "HIGH",
    openedAt: "2024-09-15",
    nextDeadline: "2025-03-15",
    description:
      "Criminal defense case for charges of alleged financial fraud.",
    notes: [
      {
        id: "n10",
        content: "Discovery received. Reviewing evidence.",
        author: "Lisa Defense",
        authorId: "attorney6",
        createdAt: "2024-10-01T11:00:00Z",
        updatedAt: "2024-10-01T11:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "8",
    title: "Greenwood Trust Fund",
    clientId: "8",
    client: "James Greenwood",
    status: "PENDING",
    practiceArea: "ESTATE_PLANNING",
    priority: "MEDIUM",
    openedAt: "2024-07-22",
    nextDeadline: "2024-12-20",
    description:
      "Creation of a complex family trust fund with multiple beneficiaries.",
    notes: [],
  },
  {
    id: "9",
    title: "Rivera H-1B Visa Application",
    clientId: "9",
    client: "Alejandro Rivera",
    status: "ACTIVE",
    practiceArea: "IMMIGRATION",
    priority: "HIGH",
    openedAt: "2024-10-18",
    nextDeadline: "2025-01-31",
    description: "H-1B visa application for specialized engineer position.",
    notes: [
      {
        id: "n11",
        content: "LCA certified. Form I-129 prepared for filing.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-11-05T15:30:00Z",
        updatedAt: "2024-11-05T15:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "10",
    title: "Peterson Adoption Process",
    clientId: "10",
    client: "David Peterson",
    status: "ACTIVE",
    practiceArea: "FAMILY_LAW",
    priority: "HIGH",
    openedAt: "2024-08-08",
    nextDeadline: "2025-01-15",
    description: "International adoption legal proceedings and documentation.",
    notes: [
      {
        id: "n12",
        content:
          "Home study completed. Waiting for international agency approval.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-10-20T09:15:00Z",
        updatedAt: "2024-10-20T09:15:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "11",
    title: "Deportation Defense Case",
    clientId: "11",
    client: "Li Wei",
    status: "ARCHIVED",
    practiceArea: "IMMIGRATION",
    priority: "URGENT",
    openedAt: "2024-09-28",
    nextDeadline: "2025-04-05",
    description: "Defense against deportation proceedings - asylum granted.",
    notes: [
      {
        id: "n13",
        content: "Asylum granted. Case closed and archived.",
        author: "David Immigration",
        authorId: "attorney7",
        createdAt: "2024-12-18T10:45:00Z",
        updatedAt: "2024-12-18T10:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "12",
    title: "Carter Personal Injury",
    clientId: "12",
    client: "Susan Carter",
    status: "CLOSED",
    practiceArea: "PERSONAL_INJURY",
    priority: "HIGH",
    openedAt: "2024-09-10",
    nextDeadline: "2025-02-14",
    description: "Personal injury lawsuit - settled.",
    notes: [
      {
        id: "n14",
        content: "Settlement reached for $75,000. Case closed.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-12-05T14:30:00Z",
        updatedAt: "2024-12-05T14:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "13",
    title: "Anderson vs. Neighbor",
    clientId: "13",
    client: "Thomas Anderson",
    status: "PENDING",
    practiceArea: "CIVIL_LITIGATION",
    priority: "MEDIUM",
    openedAt: "2024-11-12",
    nextDeadline: "2025-02-28",
    description:
      "Property boundary dispute and nuisance claim against neighbor.",
    notes: [],
  },
  {
    id: "14",
    title: "Martin Child Custody",
    clientId: "14",
    client: "Jennifer Martin",
    status: "ACTIVE",
    practiceArea: "FAMILY_LAW",
    priority: "URGENT",
    openedAt: "2024-08-30",
    nextDeadline: "2024-12-15",
    description: "Child custody and visitation rights modification case.",
    notes: [
      {
        id: "n15",
        content:
          "Temporary custody order granted. Full hearing scheduled for January.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-11-15T16:00:00Z",
        updatedAt: "2024-11-15T16:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "15",
    title: "NexTech Equity Distribution",
    clientId: "15",
    client: "Robert Chen",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-10-01",
    nextDeadline: "2024-12-10",
    description:
      "Employee stock option plan and equity distribution legal structuring.",
    notes: [
      {
        id: "n16",
        content: "ESOP documents drafted. Review with founders scheduled.",
        author: "Corporate Attorney",
        authorId: "attorney9",
        createdAt: "2024-11-08T11:15:00Z",
        updatedAt: "2024-11-08T11:15:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "16",
    title: "Johnson Employment Discrimination",
    clientId: "16",
    client: "Amanda Johnson",
    status: "ACTIVE",
    practiceArea: "EMPLOYMENT",
    priority: "HIGH",
    openedAt: "2024-09-05",
    nextDeadline: "2025-03-01",
    description: "Employment discrimination case against former employer.",
    notes: [
      {
        id: "n17",
        content: "EEOC charge filed. Investigation ongoing.",
        author: "Richard Labor",
        authorId: "attorney4",
        createdAt: "2024-10-25T09:45:00Z",
        updatedAt: "2024-10-25T09:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "17",
    title: "Miller Series A Funding",
    clientId: "17",
    client: "Brian Miller",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "HIGH",
    openedAt: "2024-07-22",
    nextDeadline: "2024-12-20",
    description: "Series A funding round and investor agreements.",
    notes: [
      {
        id: "n18",
        content: "Term sheet received from lead investor. Reviewing terms.",
        author: "Corporate Attorney",
        authorId: "attorney9",
        createdAt: "2024-11-12T13:20:00Z",
        updatedAt: "2024-11-12T13:20:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "18",
    title: "TechVantage Data Privacy",
    clientId: "19",
    client: "TechVantage Solutions",
    status: "ACTIVE",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "MEDIUM",
    openedAt: "2024-10-10",
    nextDeadline: "2025-04-10",
    description: "Data privacy compliance and GDPR implementation.",
    notes: [
      {
        id: "n19",
        content:
          "Initial privacy audit completed. Implementing recommendations.",
        author: "Privacy Counsel",
        authorId: "attorney11",
        createdAt: "2024-11-01T14:00:00Z",
        updatedAt: "2024-11-01T14:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "19",
    title: "Global Manufacturing OSHA Compliance",
    clientId: "20",
    client: "Global Manufacturing Co.",
    status: "PENDING",
    practiceArea: "EMPLOYMENT",
    priority: "URGENT",
    openedAt: "2024-10-18",
    nextDeadline: "2025-01-15",
    description: "OSHA compliance and workplace safety program development.",
    notes: [
      {
        id: "n20",
        content: "Awaiting OSHA inspection report.",
        author: "Compliance Officer",
        authorId: "attorney12",
        createdAt: "2024-12-01T11:30:00Z",
        updatedAt: "2024-12-01T11:30:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "20",
    title: "Springfield Zoning Dispute",
    clientId: "23",
    client: "City of Springfield",
    status: "ACTIVE",
    practiceArea: "REAL_ESTATE",
    priority: "HIGH",
    openedAt: "2024-09-05",
    nextDeadline: "2025-01-25",
    description: "Commercial real estate zoning variance application.",
    notes: [
      {
        id: "n21",
        content:
          "Zoning hearing scheduled for December 5. Preparing presentation.",
        author: "Municipal Attorney",
        authorId: "attorney14",
        createdAt: "2024-11-10T15:45:00Z",
        updatedAt: "2024-11-10T15:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "21",
    title: "State Education Policy Review",
    clientId: "24",
    client: "State Education Department",
    status: "ARCHIVED",
    practiceArea: "GOVERNMENT",
    priority: "MEDIUM",
    openedAt: "2024-10-30",
    nextDeadline: "2025-03-15",
    description: "Review and update of state education policies - completed.",
    notes: [
      {
        id: "n22",
        content:
          "Policy review completed. Final report submitted. Case archived.",
        author: "Education Law Specialist",
        authorId: "attorney15",
        createdAt: "2024-12-15T09:45:00Z",
        updatedAt: "2024-12-15T09:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "22",
    title: "Hope Foundation Grant Compliance",
    clientId: "25",
    client: "Hope Foundation",
    status: "ACTIVE",
    practiceArea: "NON_PROFIT",
    priority: "MEDIUM",
    openedAt: "2024-09-18",
    nextDeadline: "2025-02-28",
    description: "Federal grant compliance and reporting requirements.",
    notes: [
      {
        id: "n23",
        content:
          "Quarterly grant report submitted. Next report due in January.",
        author: "Non-Profit Counsel",
        authorId: "attorney16",
        createdAt: "2024-11-15T10:00:00Z",
        updatedAt: "2024-11-15T10:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "23",
    title: "Green Earth Pollution Lawsuit",
    clientId: "26",
    client: "Green Earth Alliance",
    status: "ACTIVE",
    practiceArea: "ENVIRONMENTAL",
    priority: "HIGH",
    openedAt: "2024-10-07",
    nextDeadline: "2025-04-15",
    description:
      "Environmental pollution lawsuit against industrial manufacturer.",
    notes: [
      {
        id: "n24",
        content: "Complaint filed in federal court. Discovery pending.",
        author: "Environmental Attorney",
        authorId: "attorney17",
        createdAt: "2024-11-08T09:30:00Z",
        updatedAt: "2024-11-08T09:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "24",
    title: "Johnson Will Contest",
    clientId: "2",
    client: "Sarah Williams",
    status: "PENDING",
    practiceArea: "ESTATE_PLANNING",
    priority: "URGENT",
    openedAt: "2024-11-20",
    nextDeadline: "2025-03-20",
    description:
      "Contest of will and estate distribution among multiple heirs.",
    notes: [],
  },
  {
    id: "25",
    title: "Quantum Financial SEC Filing",
    clientId: "22",
    client: "Quantum Financial",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-10-13",
    nextDeadline: "2025-01-30",
    description: "SEC filing preparation and regulatory compliance review.",
    notes: [
      {
        id: "n25",
        content:
          "Form 10-K preparation in progress. Audit team review scheduled.",
        author: "Securities Attorney",
        authorId: "attorney13",
        createdAt: "2024-11-12T16:15:00Z",
        updatedAt: "2024-11-12T16:15:00Z",
        isPrivate: true,
      },
    ],
  },
  // NEW CASES - Adding 15 more to reach 40 total
  {
    id: "26",
    title: "TechInnovate Patent Portfolio",
    clientId: "28",
    client: "Raymond Kim",
    status: "ACTIVE",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "HIGH",
    openedAt: "2024-09-15",
    nextDeadline: "2025-03-15",
    description: "Patent portfolio management for AI software company.",
    notes: [
      {
        id: "n26",
        content:
          "Filed 3 provisional patents. Preparing non-provisional applications.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-11-20T14:15:00Z",
        updatedAt: "2024-11-20T14:15:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "27",
    title: "Wright Contract Dispute",
    clientId: "30",
    client: "Marcus Wright",
    status: "ACTIVE",
    practiceArea: "CIVIL_LITIGATION",
    priority: "MEDIUM",
    openedAt: "2024-11-15",
    nextDeadline: "2025-02-15",
    description: "Contract dispute with former business partner.",
    notes: [
      {
        id: "n27",
        content: "Demand letter sent. Awaiting response.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-11-28T09:45:00Z",
        updatedAt: "2024-11-28T09:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "28",
    title: "BioGenEx Patent Litigation",
    clientId: "32",
    client: "Franklin Zhang",
    status: "ACTIVE",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "URGENT",
    openedAt: "2024-06-20",
    nextDeadline: "2025-04-15",
    description: "Patent litigation defense for biologic drug compound.",
    notes: [
      {
        id: "n28",
        content: "Markman hearing scheduled for March.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-11-10T16:20:00Z",
        updatedAt: "2024-11-10T16:20:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "29",
    title: "County Health Malpractice Defense",
    clientId: "34",
    client: "County Health Services",
    status: "ACTIVE",
    practiceArea: "CRIMINAL_DEFENSE",
    priority: "HIGH",
    openedAt: "2024-08-01",
    nextDeadline: "2025-02-01",
    description: "Medical malpractice defense for county hospital system.",
    notes: [
      {
        id: "n29",
        content: "Two active cases in discovery phase.",
        author: "Lisa Defense",
        authorId: "attorney6",
        createdAt: "2024-11-18T11:30:00Z",
        updatedAt: "2024-11-18T11:30:00Z",
        isPrivate: true,
      },
    ],
  },
  {
    id: "30",
    title: "Nelson Divorce Proceeding",
    clientId: "35",
    client: "Rebecca Nelson",
    status: "ACTIVE",
    practiceArea: "FAMILY_LAW",
    priority: "HIGH",
    openedAt: "2024-10-10",
    nextDeadline: "2025-02-28",
    description: "Divorce proceeding with complex asset division.",
    notes: [
      {
        id: "n30",
        content:
          "Financial disclosures submitted. Settlement conference scheduled.",
        author: "Sarah FamilyLaw",
        authorId: "attorney8",
        createdAt: "2024-11-25T15:00:00Z",
        updatedAt: "2024-11-25T15:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "31",
    title: "Community Food Bank Employment Review",
    clientId: "38",
    client: "Community Food Bank",
    status: "CLOSED",
    practiceArea: "EMPLOYMENT",
    priority: "LOW",
    openedAt: "2024-10-20",
    nextDeadline: "2024-12-01",
    description: "Employment handbook review and compliance.",
    notes: [
      {
        id: "n31",
        content: "Employment handbook review completed. Case closed.",
        author: "Richard Labor",
        authorId: "attorney4",
        createdAt: "2024-12-01T13:45:00Z",
        updatedAt: "2024-12-01T13:45:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "32",
    title: "Wong Medicaid Planning",
    clientId: "39",
    client: "Victoria Wong",
    status: "ACTIVE",
    practiceArea: "ESTATE_PLANNING",
    priority: "MEDIUM",
    openedAt: "2024-11-01",
    nextDeadline: "2025-01-30",
    description: "Elder law and Medicaid planning for parent.",
    notes: [
      {
        id: "n32",
        content: "Medicaid application submitted. Awaiting determination.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2024-11-30T10:30:00Z",
        updatedAt: "2024-11-30T10:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "33",
    title: "Caldwell Commercial Lease",
    clientId: "40",
    client: "Steven Caldwell",
    status: "CLOSED",
    practiceArea: "REAL_ESTATE",
    priority: "MEDIUM",
    openedAt: "2024-07-15",
    nextDeadline: "2024-12-01",
    description: "Commercial lease negotiation for downtown property.",
    notes: [
      {
        id: "n33",
        content: "Successfully negotiated lease modification. Case closed.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-12-02T16:15:00Z",
        updatedAt: "2024-12-02T16:15:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "34",
    title: "Foster Trust Administration",
    clientId: "29",
    client: "Elizabeth Foster",
    status: "ARCHIVED",
    practiceArea: "ESTATE_PLANNING",
    priority: "LOW",
    openedAt: "2023-08-10",
    nextDeadline: "2023-10-15",
    description: "Trust administration following death of grantor - completed.",
    notes: [
      {
        id: "n34",
        content:
          "Trust administration completed. Assets distributed. Archived.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2023-10-15T14:30:00Z",
        updatedAt: "2023-10-15T14:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "35",
    title: "Martinez Trademark Registration",
    clientId: "31",
    client: "Sophia Martinez",
    status: "PENDING",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "MEDIUM",
    openedAt: "2024-12-01",
    nextDeadline: "2025-01-15",
    description: "Trademark registration for fashion brand.",
    notes: [
      {
        id: "n35",
        content: "Trademark search completed. Preparing application.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-12-10T11:00:00Z",
        updatedAt: "2024-12-10T11:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "36",
    title: "Fontaine International Trade Compliance",
    clientId: "36",
    client: "Andre Fontaine",
    status: "PENDING",
    practiceArea: "CORPORATE",
    priority: "MEDIUM",
    openedAt: "2024-12-09",
    nextDeadline: "2025-02-09",
    description: "International trade compliance and customs issues.",
    notes: [],
  },
  {
    id: "37",
    title: "Kim Software Licensing Agreement",
    clientId: "28",
    client: "Raymond Kim",
    status: "ACTIVE",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "MEDIUM",
    openedAt: "2024-10-15",
    nextDeadline: "2025-01-15",
    description:
      "Drafting software licensing agreements for enterprise clients.",
    notes: [
      {
        id: "n36",
        content: "First draft completed. Client review in progress.",
        author: "Michael IP",
        authorId: "attorney3",
        createdAt: "2024-11-15T10:00:00Z",
        updatedAt: "2024-11-15T10:00:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "38",
    title: "Caldwell Property Acquisition",
    clientId: "40",
    client: "Steven Caldwell",
    status: "ACTIVE",
    practiceArea: "REAL_ESTATE",
    priority: "HIGH",
    openedAt: "2024-11-01",
    nextDeadline: "2025-01-30",
    description: "Commercial property acquisition and due diligence.",
    notes: [
      {
        id: "n37",
        content: "Purchase agreement drafted. Title search in progress.",
        author: "John Attorney",
        authorId: "attorney1",
        createdAt: "2024-11-20T09:30:00Z",
        updatedAt: "2024-11-20T09:30:00Z",
        isPrivate: false,
      },
    ],
  },
  {
    id: "39",
    title: "O'Connor Estate Plan",
    clientId: "27",
    client: "Patricia O'Connor",
    status: "PENDING",
    practiceArea: "ESTATE_PLANNING",
    priority: "LOW",
    openedAt: "2024-12-12",
    nextDeadline: "2025-02-12",
    description: "Estate planning for blended family situation.",
    notes: [],
  },
  {
    id: "40",
    title: "Jenkins Estate Administration",
    clientId: "37",
    client: "Harold Jenkins",
    status: "ARCHIVED",
    practiceArea: "ESTATE_PLANNING",
    priority: "LOW",
    openedAt: "2022-11-01",
    nextDeadline: "2022-12-15",
    description: "Estate plan completion - archived.",
    notes: [
      {
        id: "n38",
        content: "Estate plan complete. Case archived.",
        author: "Emily Attorney",
        authorId: "attorney2",
        createdAt: "2022-12-15T14:30:00Z",
        updatedAt: "2022-12-15T14:30:00Z",
        isPrivate: false,
      },
    ],
  },
];

// ============ Invoices ============
export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2024-001",
    clientId: "1",
    clientName: "Robert Smith",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    issueDate: "2024-11-15",
    dueDate: "2024-12-15",
    items: [
      {
        id: "li1",
        description: "Initial Consultation",
        quantity: 2,
        rate: 250,
        amount: 500,
      },
      {
        id: "li2",
        description: "Document Review",
        quantity: 10,
        rate: 200,
        amount: 2000,
      },
      {
        id: "li3",
        description: "Court Filing Preparation",
        quantity: 15,
        rate: 200,
        amount: 3000,
      },
    ],
    subtotal: 5500,
    taxRate: 0,
    taxAmount: 0,
    total: 5500,
    status: "PAID",
    paidDate: "2024-12-10",
    notes: "Payment received via wire transfer.",
    createdAt: "2024-11-15T10:30:00Z",
    updatedAt: "2024-12-10T14:20:00Z",
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2024-002",
    clientId: "18",
    clientName: "Davis Corporation",
    caseId: "3",
    caseName: "Davis Corp Merger",
    issueDate: "2024-12-01",
    dueDate: "2024-12-31",
    items: [
      {
        id: "li4",
        description: "Merger Due Diligence",
        quantity: 40,
        rate: 300,
        amount: 12000,
      },
      {
        id: "li5",
        description: "Contract Drafting",
        quantity: 10,
        rate: 300,
        amount: 3000,
      },
    ],
    subtotal: 15000,
    taxRate: 0,
    taxAmount: 0,
    total: 15000,
    status: "SENT",
    notes: "Net 30 payment terms.",
    createdAt: "2024-12-01T09:15:00Z",
    updatedAt: "2024-12-01T09:15:00Z",
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2024-003",
    clientId: "6",
    clientName: "Emily Brown",
    caseId: "6",
    caseName: "Brown Property Sale",
    issueDate: "2024-11-20",
    dueDate: "2024-12-20",
    items: [
      {
        id: "li6",
        description: "Property Title Search",
        quantity: 5,
        rate: 200,
        amount: 1000,
      },
      {
        id: "li7",
        description: "Contract Review",
        quantity: 10,
        rate: 200,
        amount: 2000,
      },
      {
        id: "li8",
        description: "Closing Preparation",
        quantity: 2.5,
        rate: 200,
        amount: 500,
      },
    ],
    subtotal: 3500,
    taxRate: 0,
    taxAmount: 0,
    total: 3500,
    status: "OVERDUE",
    notes: "Follow up required for payment.",
    createdAt: "2024-11-20T13:45:00Z",
    updatedAt: "2024-11-20T13:45:00Z",
  },
  {
    id: "inv4",
    invoiceNumber: "INV-2024-004",
    clientId: "22",
    clientName: "Quantum Financial",
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    issueDate: "2024-12-05",
    dueDate: "2025-01-05",
    items: [
      {
        id: "li9",
        description: "SEC Filing Review",
        quantity: 20,
        rate: 350,
        amount: 7000,
      },
      {
        id: "li10",
        description: "Compliance Consultation",
        quantity: 8,
        rate: 350,
        amount: 2800,
      },
    ],
    subtotal: 9800,
    taxRate: 0,
    taxAmount: 0,
    total: 9800,
    status: "DRAFT",
    notes: "Pending internal review.",
    createdAt: "2024-12-05T11:00:00Z",
    updatedAt: "2024-12-05T11:00:00Z",
  },
  {
    id: "inv5",
    invoiceNumber: "INV-2024-005",
    clientId: "19",
    clientName: "TechVantage Solutions",
    caseId: "18",
    caseName: "TechVantage Data Privacy",
    issueDate: "2024-11-10",
    dueDate: "2024-12-10",
    items: [
      {
        id: "li11",
        description: "Privacy Audit",
        quantity: 15,
        rate: 275,
        amount: 4125,
      },
      {
        id: "li12",
        description: "Policy Drafting",
        quantity: 12,
        rate: 275,
        amount: 3300,
      },
    ],
    subtotal: 7425,
    taxRate: 0,
    taxAmount: 0,
    total: 7425,
    status: "PARTIALLY_PAID",
    paidDate: "2024-11-25",
    notes: "Partial payment received. Balance: $3,000",
    createdAt: "2024-11-10T10:00:00Z",
    updatedAt: "2024-11-25T15:30:00Z",
  },
  {
    id: "inv6",
    invoiceNumber: "INV-2024-006",
    clientId: "23",
    clientName: "City of Springfield",
    caseId: "20",
    caseName: "Springfield Zoning Dispute",
    issueDate: "2024-12-01",
    dueDate: "2024-12-31",
    items: [
      {
        id: "li13",
        description: "Legal Research",
        quantity: 6,
        rate: 225,
        amount: 1350,
      },
      {
        id: "li14",
        description: "Hearing Preparation",
        quantity: 10,
        rate: 225,
        amount: 2250,
      },
    ],
    subtotal: 3600,
    taxRate: 0,
    taxAmount: 0,
    total: 3600,
    status: "SENT",
    notes: "Net 30 payment terms.",
    createdAt: "2024-12-01T14:20:00Z",
    updatedAt: "2024-12-01T14:20:00Z",
  },
];

// ============ Documents ============
export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "Complaint_Filed.pdf",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    uploadDate: "2024-08-20T11:30:00Z",
    size: "2.4 MB",
    type: "LEGAL_FILING",
    description: "Initial complaint filed with Superior Court",
  },
  {
    id: "d2",
    name: "Contract_Exhibit_A.pdf",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    uploadDate: "2024-08-22T15:45:00Z",
    size: "1.2 MB",
    type: "EVIDENCE",
    description: "Signed contract between parties",
  },
  {
    id: "d3",
    name: "Will_Draft_v2.docx",
    caseId: "2",
    caseName: "Estate of Williams",
    uploadDate: "2024-09-05T13:20:00Z",
    size: "456 KB",
    type: "DRAFT",
    description: "Revised will incorporating client feedback",
  },
  {
    id: "d4",
    name: "Merger_Agreement.pdf",
    caseId: "3",
    caseName: "Davis Corp Merger",
    uploadDate: "2024-07-15T10:00:00Z",
    size: "5.8 MB",
    type: "CONTRACT",
    description: "Final merger agreement between Davis Corp and German partner",
  },
  {
    id: "d5",
    name: "Discovery_Request.pdf",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    uploadDate: "2024-09-10T09:15:00Z",
    size: "890 KB",
    type: "PLEADING",
    description: "First set of interrogatories to defendant",
  },
  {
    id: "d6",
    name: "Medical_Records.pdf",
    caseId: "12",
    caseName: "Carter Personal Injury",
    uploadDate: "2024-10-15T14:30:00Z",
    size: "3.2 MB",
    type: "EVIDENCE",
    description: "Complete medical records from treating physician",
  },
  {
    id: "d7",
    name: "H-1B_Petition.pdf",
    caseId: "9",
    caseName: "Rivera H-1B Visa Application",
    uploadDate: "2024-11-01T11:45:00Z",
    size: "4.1 MB",
    type: "LEGAL_FILING",
    description: "Form I-129 and supporting documentation",
  },
  {
    id: "d8",
    name: "SEC_Filing_Draft.docx",
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    uploadDate: "2024-11-15T16:20:00Z",
    size: "1.8 MB",
    type: "DRAFT",
    description: "Draft Form 10-K for internal review",
  },
  {
    id: "d9",
    name: "Zoning_Application.pdf",
    caseId: "20",
    caseName: "Springfield Zoning Dispute",
    uploadDate: "2024-11-10T10:30:00Z",
    size: "2.2 MB",
    type: "PLEADING",
    description: "Variance application submitted to zoning board",
  },
  {
    id: "d10",
    name: "Adoption_Petition.pdf",
    caseId: "10",
    caseName: "Peterson Adoption Process",
    uploadDate: "2024-09-20T13:15:00Z",
    size: "1.5 MB",
    type: "LEGAL_FILING",
    description: "Petition for adoption filed with family court",
  },
];

// ============ Meetings ============
export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    title: "Case Strategy Session",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    date: "2024-12-10",
    time: "10:00",
    duration: 90,
    type: "CASE_STRATEGY",
    status: "SCHEDULED",
    location: "Conference Room A",
    attendees: ["John Attorney", "Robert Smith", "Sarah Paralegal"],
    agenda: "Review settlement offer and discuss trial strategy",
    notes: "Client open to settlement if terms are favorable",
    createdAt: "2024-11-20T09:00:00Z",
    updatedAt: "2024-11-20T09:00:00Z",
  },
  {
    id: "m2",
    title: "Phone Call with Opposing Counsel",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    date: "2024-12-05",
    time: "14:30",
    duration: 30,
    type: "PHONE_CALL",
    status: "COMPLETED",
    attendees: ["John Attorney", "Jane Defense"],
    agenda: "Discuss discovery schedule and potential settlement",
    notes: "Opposing counsel requested 30-day extension for discovery",
    createdAt: "2024-11-18T11:00:00Z",
    updatedAt: "2024-12-05T15:00:00Z",
  },
  {
    id: "m3",
    title: "Merger Board Presentation",
    caseId: "3",
    caseName: "Davis Corp Merger",
    date: "2024-12-08",
    time: "09:00",
    duration: 120,
    type: "CLIENT_MEETING",
    status: "COMPLETED",
    location: "Davis Corp HQ - Board Room",
    attendees: ["M&A Specialist", "Davis Corp Board", "German Partners"],
    agenda: "Final merger terms and timeline",
    notes: "Board approved merger. Moving to shareholder vote.",
    createdAt: "2024-11-01T10:30:00Z",
    updatedAt: "2024-12-08T11:00:00Z",
  },
  {
    id: "m4",
    title: "Immigration Consultation",
    caseId: "9",
    caseName: "Rivera H-1B Visa Application",
    date: "2024-12-12",
    time: "11:00",
    duration: 60,
    type: "INITIAL_CONSULTATION",
    status: "SCHEDULED",
    location: "Video Conference",
    attendees: ["David Immigration", "Alejandro Rivera", "HR Manager"],
    agenda: "Review H-1B petition status and next steps",
    notes: "Premium processing requested",
    createdAt: "2024-11-25T14:15:00Z",
    updatedAt: "2024-11-25T14:15:00Z",
  },
  {
    id: "m5",
    title: "Deposition Preparation",
    caseId: "12",
    caseName: "Carter Personal Injury",
    date: "2024-12-15",
    time: "13:00",
    duration: 120,
    type: "DEPOSITION",
    status: "SCHEDULED",
    location: "Conference Room B",
    attendees: ["John Attorney", "Susan Carter", "Expert Witness"],
    agenda: "Prepare client for deposition",
    notes: "Focus on accident details and medical treatment timeline",
    createdAt: "2024-11-28T09:45:00Z",
    updatedAt: "2024-11-28T09:45:00Z",
  },
  {
    id: "m6",
    title: "SEC Filing Review",
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    date: "2024-12-14",
    time: "15:00",
    duration: 90,
    type: "INTERNAL_REVIEW",
    status: "SCHEDULED",
    location: "Virtual",
    attendees: ["Securities Attorney", "Quantum CFO", "Audit Team"],
    agenda: "Final review of Form 10-K before filing",
    notes: "Focus on risk factors and financial disclosures",
    createdAt: "2024-12-01T16:30:00Z",
    updatedAt: "2024-12-01T16:30:00Z",
  },
  {
    id: "m7",
    title: "Mediation Session",
    caseId: "14",
    caseName: "Martin Child Custody",
    date: "2024-12-18",
    time: "09:30",
    duration: 180,
    type: "MEDIATION",
    status: "SCHEDULED",
    location: "Family Court - Mediation Center",
    attendees: ["Sarah FamilyLaw", "Jennifer Martin", "Ex-Spouse", "Mediator"],
    agenda: "Attempt to reach custody agreement",
    notes: "Both parties have expressed willingness to compromise",
    createdAt: "2024-11-15T11:20:00Z",
    updatedAt: "2024-11-15T11:20:00Z",
  },
  {
    id: "m8",
    title: "Zoning Hearing",
    caseId: "20",
    caseName: "Springfield Zoning Dispute",
    date: "2024-12-05",
    time: "10:00",
    duration: 120,
    type: "COURT_HEARING",
    status: "COMPLETED",
    location: "Springfield Municipal Building",
    attendees: ["Municipal Attorney", "City Planner", "Zoning Board"],
    agenda: "Present variance application",
    notes: "Continuance granted to January 15",
    createdAt: "2024-11-01T13:00:00Z",
    updatedAt: "2024-12-05T12:30:00Z",
  },
  {
    id: "m9",
    title: "Estate Planning Review",
    caseId: "2",
    caseName: "Estate of Williams",
    date: "2024-12-20",
    time: "14:00",
    duration: 90,
    type: "CLIENT_MEETING",
    status: "SCHEDULED",
    location: "Office",
    attendees: ["Emily Attorney", "Sarah Williams", "Financial Advisor"],
    agenda: "Review updated estate plan documents",
    notes: "Client considering adding charitable trust",
    createdAt: "2024-11-10T10:15:00Z",
    updatedAt: "2024-11-10T10:15:00Z",
  },
  {
    id: "m10",
    title: "Expert Witness Interview",
    caseId: "23",
    caseName: "Green Earth Pollution Lawsuit",
    date: "2024-12-17",
    time: "11:00",
    duration: 90,
    type: "EXPERT_CONSULTATION",
    status: "SCHEDULED",
    location: "Video Conference",
    attendees: ["Environmental Attorney", "Dr. Environmental Scientist"],
    agenda: "Evaluate pollution impact evidence",
    notes: "Expert has previously testified in similar cases",
    createdAt: "2024-11-22T15:45:00Z",
    updatedAt: "2024-11-22T15:45:00Z",
  },
];

// ============ Tasks ============
export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Draft settlement agreement",
    description: "Prepare settlement agreement based on mediation discussions",
    dueDate: "2025-02-08",
    priority: "HIGH",
    status: "IN_PROGRESS",
    completed: false,
    caseId: "6",
    caseName: "Brown Property Sale",
    assignedTo: "Alexandra Mitchell",
    createdAt: "2024-12-01T09:00:00Z",
    updatedAt: "2024-12-01T09:00:00Z",
  },
  {
    id: "t2",
    title: "Review discovery documents",
    description: "Review 500 pages of discovery documents from defendant",
    dueDate: "2025-02-07",
    priority: "HIGH",
    status: "TODO",
    completed: false,
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    assignedTo: "Alexandra Mitchell",
    createdAt: "2024-12-02T10:30:00Z",
    updatedAt: "2024-12-02T10:30:00Z",
  },
  {
    id: "t3",
    title: "Prepare immigration forms",
    description: "Complete Form I-485 and supporting documents",
    dueDate: "2025-02-10",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    completed: false,
    caseId: "5",
    caseName: "Garcia Immigration",
    assignedTo: "David Immigration",
    createdAt: "2024-12-03T14:15:00Z",
    updatedAt: "2024-12-03T14:15:00Z",
  },
  {
    id: "t4",
    title: "Client meeting prep",
    description: "Prepare presentation and documents for merger meeting",
    dueDate: "2025-02-09",
    priority: "MEDIUM",
    status: "TODO",
    completed: false,
    caseId: "3",
    caseName: "Davis Corp Merger",
    assignedTo: "M&A Specialist",
    createdAt: "2024-12-04T11:45:00Z",
    updatedAt: "2024-12-04T11:45:00Z",
  },
  {
    id: "t5",
    title: "File court response",
    description: "File opposition to motion for summary judgment",
    dueDate: "2025-02-06",
    priority: "URGENT",
    status: "BLOCKED",
    completed: false,
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    assignedTo: "John Attorney",
    createdAt: "2024-12-01T16:20:00Z",
    updatedAt: "2024-12-01T16:20:00Z",
  },
  {
    id: "t6",
    title: "SEC filing preparation",
    description: "Compile exhibits for Form 10-K filing",
    dueDate: "2025-01-30",
    priority: "HIGH",
    status: "IN_PROGRESS",
    completed: false,
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    assignedTo: "Securities Attorney",
    createdAt: "2024-12-01T13:00:00Z",
    updatedAt: "2024-12-01T13:00:00Z",
  },
  {
    id: "t7",
    title: "Witness interview",
    description: "Interview eyewitness to accident",
    dueDate: "2025-02-15",
    priority: "MEDIUM",
    status: "TODO",
    completed: false,
    caseId: "12",
    caseName: "Carter Personal Injury",
    assignedTo: "John Attorney",
    createdAt: "2024-12-05T09:30:00Z",
    updatedAt: "2024-12-05T09:30:00Z",
  },
  {
    id: "t8",
    title: "Privacy policy update",
    description: "Update privacy policy to comply with new regulations",
    dueDate: "2025-01-15",
    priority: "MEDIUM",
    status: "IN_REVIEW",
    completed: false,
    caseId: "18",
    caseName: "TechVantage Data Privacy",
    assignedTo: "Privacy Counsel",
    createdAt: "2024-11-20T10:15:00Z",
    updatedAt: "2024-12-01T14:30:00Z",
  },
  {
    id: "t9",
    title: "OSHA compliance report",
    description: "Prepare final OSHA compliance report",
    dueDate: "2025-01-10",
    priority: "URGENT",
    status: "IN_PROGRESS",
    completed: false,
    caseId: "19",
    caseName: "Global Manufacturing OSHA Compliance",
    assignedTo: "Compliance Officer",
    createdAt: "2024-11-25T11:00:00Z",
    updatedAt: "2024-11-25T11:00:00Z",
  },
  {
    id: "t10",
    title: "Adoption home study",
    description: "Coordinate with social worker for adoption home study",
    dueDate: "2025-01-05",
    priority: "HIGH",
    status: "IN_PROGRESS",
    completed: false,
    caseId: "10",
    caseName: "Peterson Adoption Process",
    assignedTo: "Sarah FamilyLaw",
    createdAt: "2024-11-28T15:45:00Z",
    updatedAt: "2024-11-28T15:45:00Z",
  },
];

// ============ Communications ============
export const mockCommunications: Communication[] = [
  {
    id: "cm1",
    clientId: "1",
    clientName: "Robert Smith",
    type: "EMAIL",
    status: "READ",
    direction: "INBOUND",
    subject: "Re: Settlement offer review",
    content: "Client reviewed settlement offer and has counter-proposal",
    time: "30 min ago",
    unread: false,
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "cm2",
    clientId: "18",
    clientName: "Davis Corporation",
    type: "CALL",
    status: "UNREAD",
    direction: "OUTBOUND",
    subject: "Merger timeline discussion",
    content: "Discussed revised merger timeline with GC",
    time: "2 hours ago",
    unread: true,
    caseId: "3",
    caseName: "Davis Corp Merger",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "cm3",
    clientId: "5",
    clientName: "Maria Garcia",
    type: "EMAIL",
    status: "READ",
    direction: "INBOUND",
    subject: "Visa application update",
    content: "Biometrics appointment scheduled for next week",
    time: "Yesterday",
    unread: false,
    caseId: "5",
    caseName: "Garcia Immigration",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "cm4",
    clientId: "6",
    clientName: "Emily Brown",
    type: "MESSAGE",
    status: "READ",
    direction: "INBOUND",
    subject: "Closing date confirmation",
    content: "Buyer confirmed January 10 closing date",
    time: "Yesterday",
    unread: false,
    caseId: "6",
    caseName: "Brown Property Sale",
    createdAt: new Date(Date.now() - 90000000).toISOString(),
  },
  {
    id: "cm5",
    clientId: "22",
    clientName: "Quantum Financial",
    type: "EMAIL",
    status: "UNREAD",
    direction: "OUTBOUND",
    subject: "SEC comment letter",
    content: "Received comment letter from SEC on Form 10-K",
    time: "3 hours ago",
    unread: true,
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "cm6",
    clientId: "23",
    clientName: "City of Springfield",
    type: "CALL",
    status: "READ",
    direction: "INBOUND",
    subject: "Zoning hearing continuance",
    content: "Zoning board granted continuance to January 15",
    time: "Yesterday",
    unread: false,
    caseId: "20",
    caseName: "Springfield Zoning Dispute",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// ============ Schedule ============
export const mockSchedule = [
  {
    id: "ms1",
    title: "Client Call - Robert Smith",
    time: "10:00 AM",
    duration: "30 min",
    type: "call",
    hasVideoLink: true,
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    date: new Date().toISOString().split("T")[0],
  },
  {
    id: "ms2",
    title: "Deposition Prep - Carter",
    time: "2:00 PM",
    duration: "1 hour",
    type: "meeting",
    hasVideoLink: false,
    caseId: "12",
    caseName: "Carter Personal Injury",
    date: new Date().toISOString().split("T")[0],
  },
  {
    id: "ms3",
    title: "Court Hearing - Smith",
    time: "3:30 PM",
    duration: "2 hours",
    type: "hearing",
    hasVideoLink: false,
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
  },
  {
    id: "ms4",
    title: "Mediation - Martin",
    time: "9:30 AM",
    duration: "3 hours",
    type: "mediation",
    hasVideoLink: false,
    caseId: "14",
    caseName: "Martin Child Custody",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
  },
  {
    id: "ms5",
    title: "SEC Filing Review",
    time: "3:00 PM",
    duration: "1.5 hours",
    type: "video",
    hasVideoLink: true,
    caseId: "25",
    caseName: "Quantum Financial SEC Filing",
    date: new Date(Date.now() + 259200000).toISOString().split("T")[0],
  },
];

// ============ Dashboard Chart Data ============
export const revenueData = [
  { month: "Jul", revenue: 42000 },
  { month: "Aug", revenue: 38000 },
  { month: "Sep", revenue: 52000 },
  { month: "Oct", revenue: 48000 },
  { month: "Nov", revenue: 55000 },
  { month: "Dec", revenue: 48250 },
];

export const casesByPracticeArea = [
  { area: "Civil Litigation", count: 8, fill: "hsl(210, 100%, 63%)" },
  { area: "Estate Planning", count: 5, fill: "hsl(145, 63%, 49%)" },
  { area: "Corporate Law", count: 6, fill: "hsl(35, 91%, 62%)" },
  { area: "Family Law", count: 4, fill: "hsl(0, 86%, 69%)" },
  { area: "Immigration", count: 3, fill: "hsl(270, 60%, 60%)" },
  { area: "Real Estate", count: 2, fill: "hsl(195, 83%, 60%)" },
];

export const caseStatusData = [
  { name: "Active", value: 18, fill: "hsl(210, 100%, 63%)" },
  { name: "Pending", value: 5, fill: "hsl(35, 91%, 62%)" },
  { name: "Closed", value: 2, fill: "hsl(145, 63%, 49%)" },
];

export const upcomingDeadlines = [
  {
    id: "1",
    task: "Motion Response",
    case: "Smith vs. Johnson Corp",
    caseId: "1",
    dueDate: "2024-12-23",
    daysUntil: 0,
  },
  {
    id: "2",
    task: "Document Filing",
    case: "Estate of Williams",
    caseId: "2",
    dueDate: "2024-12-24",
    daysUntil: 1,
  },
  {
    id: "3",
    task: "Discovery Deadline",
    case: "Davis Corp Merger",
    caseId: "3",
    dueDate: "2024-12-28",
    daysUntil: 5,
  },
  {
    id: "4",
    task: "Court Hearing",
    case: "Garcia Immigration",
    caseId: "5",
    dueDate: "2025-01-05",
    daysUntil: 13,
  },
  {
    id: "5",
    task: "Zoning Hearing",
    case: "Springfield Zoning Dispute",
    caseId: "20",
    dueDate: "2025-01-15",
    daysUntil: 23,
  },
];

// ============ Exports ============
// export {
//   mockClients,
//   mockCases,
//   mockInvoices,
//   mockDocuments,
//   mockMeetings,
//   mockTasks,
//   mockCommunications,
//   mockSchedule,
// };
