import { Case } from "@/types/case";
import { Client } from "@/types/client";
import { Invoice } from "@/types/invoice";
import { Meeting, ScheduledMeeting } from "@/types/meeting";
import { Document } from "@/types/document";
import { Task } from "@/types/task";
import { Communication } from "@/types/communication";

export const user = {
  firstName: "Fernando",
  lastName: "Cruz",
  role: "ATTORNEY",
  src: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
};

export const firm = {
  id: "firm_123",
  name: "LawFirm",
};

export const companyData = {
  id: "Company_456",
  name: "TechCorp",
  log: "https://techcorp.com/logo.png",
  description:
    "TechCorp is a leading technology company specializing in innovative solutions.",
  shortDescription: "Leading technology solutions provider.",
  branding: "Process Manager",
  address: "123 Tech Street, Silicon Valley, CA",
  phone: "+1 (555) 123-4567",
  email: "info@techcorp.com",
};

export const mockCases: Case[] = [
  {
    id: "1",
    title: "Smith vs. Johnson Corp",
    client: "Robert Smith",
    clientId: "c1",
    status: "ACTIVE",
    practiceArea: "CIVIL_LITIGATION",
    priority: "HIGH",
    openedAt: "2024-08-15",
    nextDeadline: "2024-12-28",
    description:
      "Civil litigation case involving breach of contract dispute with Johnson Corporation.",
    notes: [
      {
        id: "n1",
        content:
          "Initial consultation completed. Client provided all relevant documents.",
        createdAt: "2024-08-15T10:00:00",
        author: "John Attorney",
      },
      {
        id: "n2",
        content: "Filed initial complaint with the court.",
        createdAt: "2024-08-20T14:30:00",
        author: "John Attorney",
      },
    ],
  },
  {
    id: "2",
    title: "Estate of Williams",
    client: "Sarah Williams",
    clientId: "c2",
    status: "PENDING",
    practiceArea: "ESTATE_PLANNING",
    priority: "MEDIUM",
    openedAt: "2024-09-01",
    nextDeadline: "2024-12-30",
    description:
      "Estate planning and will preparation for the Williams family.",
    notes: [],
  },
  {
    id: "3",
    title: "Davis Corp Merger",
    client: "Davis Corporation",
    clientId: "c3",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-07-10",
    nextDeadline: "2025-01-15",
    description:
      "Handling merger and acquisition documentation for Davis Corporation.",
    notes: [],
  },
  {
    id: "4",
    title: "Thompson Divorce",
    client: "Michael Thompson",
    clientId: "c4",
    status: "CLOSED",
    practiceArea: "FAMILY_LAW",
    priority: "LOW",
    openedAt: "2024-03-20",
    nextDeadline: "2024-11-30",
    description: "Divorce proceedings and asset division for Michael Thompson.",
    notes: [],
  },
  {
    id: "5",
    title: "Garcia Immigration",
    client: "Maria Garcia",
    clientId: "c5",
    status: "ACTIVE",
    practiceArea: "INMIGRATION",
    priority: "LOW",
    openedAt: "2024-10-05",
    nextDeadline: "2025-02-20",
    description: "Immigration visa application and documentation.",
    notes: [],
  },
  {
    id: "6",
    title: "Brown Property Sale",
    client: "Emily Brown",
    clientId: "c6",
    status: "PENDING",
    practiceArea: "REAL_ESTATE",
    priority: "LOW",
    openedAt: "2024-11-01",
    nextDeadline: "2025-01-10",
    description: "Commercial property sale documentation and closing.",
    notes: [],
  },
  {
    id: "7",
    title: "State vs. Rodriguez",
    client: "Carlos Rodriguez",
    clientId: "c7",
    status: "ACTIVE",
    practiceArea: "CRIMINAL_DEFENSE",
    priority: "LOW",
    openedAt: "2024-09-15",
    nextDeadline: "2025-03-15",
    description:
      "Criminal defense case for charges of alleged financial fraud.",
    notes: [
      {
        id: "n7-1",
        content: "Client arraignment completed. Pleaded not guilty.",
        createdAt: "2024-09-20T09:15:00",
        author: "Lisa Defense",
      },
    ],
  },
  {
    id: "8",
    title: "TechVibe Patent Infringement",
    client: "TechVibe Innovations",
    clientId: "c8",
    status: "PENDING",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "LOW",
    openedAt: "2024-10-10",
    nextDeadline: "2025-04-10",
    description:
      "Patent infringement lawsuit regarding wireless charging technology.",
    notes: [],
  },
  {
    id: "9",
    title: "Martin Child Custody",
    client: "Jennifer Martin",
    clientId: "c9",
    status: "ACTIVE",
    practiceArea: "FAMILY_LAW",
    priority: "LOW",
    openedAt: "2024-08-30",
    nextDeadline: "2024-12-15",
    description: "Child custody and visitation rights modification case.",
    notes: [
      {
        id: "n9-1",
        content: "Mediation session scheduled for next week.",
        createdAt: "2024-11-01T14:00:00",
        author: "Sarah FamilyLaw",
      },
    ],
  },
  {
    id: "10",
    title: "Greenwood Trust Fund",
    client: "James Greenwood",
    clientId: "c10",
    status: "ACTIVE",
    practiceArea: "ESTATE_PLANNING",
    priority: "LOW",
    openedAt: "2024-07-22",
    nextDeadline: "2024-12-20",
    description:
      "Creation of a complex family trust fund with multiple beneficiaries.",
    notes: [],
  },
  {
    id: "11",
    title: "GlobalCorp IPO Preparation",
    client: "GlobalCorp Inc.",
    clientId: "c11",
    status: "PENDING",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-11-05",
    nextDeadline: "2025-05-30",
    description:
      "Legal preparation and documentation for initial public offering.",
    notes: [],
  },
  {
    id: "12",
    title: "Rivera H-1B Visa Application",
    client: "Alejandro Rivera",
    clientId: "c12",
    status: "ACTIVE",
    practiceArea: "INMIGRATION",
    priority: "HIGH",
    openedAt: "2024-10-18",
    nextDeadline: "2025-01-31",
    description: "H-1B visa application for specialized engineer position.",
    notes: [
      {
        id: "n12-1",
        content: "All employer documentation received and verified.",
        createdAt: "2024-10-25T11:30:00",
        author: "David Immigration",
      },
    ],
  },
  {
    id: "13",
    title: "Lakeside Plaza Acquisition",
    client: "Metro Properties LLC",
    clientId: "c13",
    status: "ACTIVE",
    practiceArea: "REAL_ESTATE",
    priority: "MEDIUM",
    openedAt: "2024-09-05",
    nextDeadline: "2025-01-25",
    description: "Commercial real estate acquisition of a shopping plaza.",
    notes: [],
  },
  {
    id: "14",
    title: "Anderson vs. Neighbor",
    client: "Thomas Anderson",
    clientId: "c14",
    status: "PENDING",
    practiceArea: "CIVIL_LITIGATION",
    priority: "MEDIUM",
    openedAt: "2024-11-12",
    nextDeadline: "2025-02-28",
    description:
      "Property boundary dispute and nuisance claim against neighbor.",
    notes: [],
  },
  {
    id: "15",
    title: "Software Copyright Dispute",
    client: "CodeCraft Studios",
    clientId: "c15",
    status: "CLOSED",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "LOW",
    openedAt: "2024-02-14",
    nextDeadline: "2024-06-30",
    description:
      "Copyright infringement case regarding proprietary software code.",
    notes: [
      {
        id: "n15-1",
        content: "Case settled out of court. Confidentiality agreement signed.",
        createdAt: "2024-06-15T16:45:00",
        author: "Michael IP",
      },
    ],
  },
  {
    id: "16",
    title: "Peterson Adoption Process",
    client: "David & Emma Peterson",
    clientId: "c16",
    status: "ACTIVE",
    practiceArea: "FAMILY_LAW",
    priority: "HIGH",
    openedAt: "2024-08-08",
    nextDeadline: "2025-01-15",
    description: "International adoption legal proceedings and documentation.",
    notes: [],
  },
  {
    id: "17",
    title: "Historic Building Renovation",
    client: "Preservation Society",
    clientId: "c17",
    status: "ARCHIVED",
    practiceArea: "REAL_ESTATE",
    priority: "URGENT",
    openedAt: "2023-05-10",
    nextDeadline: "2024-03-01",
    description:
      "Zoning and permit approvals for historic building renovation project.",
    notes: [
      {
        id: "n17-1",
        content: "All permits approved. Project completed successfully.",
        createdAt: "2024-03-10T10:20:00",
        author: "Robert RealEstate",
      },
    ],
  },
  {
    id: "18",
    title: "Startup Equity Distribution",
    client: "NexTech Startup",
    clientId: "c18",
    status: "ACTIVE",
    practiceArea: "CORPORATE",
    priority: "URGENT",
    openedAt: "2024-10-01",
    nextDeadline: "2024-12-10",
    description:
      "Employee stock option plan and equity distribution legal structuring.",
    notes: [],
  },
  {
    id: "19",
    title: "Deportation Defense Case",
    client: "Li Wei",
    clientId: "c19",
    status: "ACTIVE",
    practiceArea: "INMIGRATION",
    priority: "MEDIUM",
    openedAt: "2024-09-28",
    nextDeadline: "2025-04-05",
    description:
      "Defense against deportation proceedings and asylum application.",
    notes: [
      {
        id: "n19-1",
        content: "Emergency stay granted. Full hearing scheduled.",
        createdAt: "2024-10-05T13:15:00",
        author: "David Immigration",
      },
    ],
  },
  {
    id: "20",
    title: "Johnson Will Contest",
    client: "Johnson Family Heirs",
    clientId: "c20",
    status: "PENDING",
    practiceArea: "ESTATE_PLANNING",
    priority: "URGENT",
    openedAt: "2024-11-20",
    nextDeadline: "2025-03-20",
    description:
      "Contest of will and estate distribution among multiple heirs.",
    notes: [],
  },
  {
    id: "21",
    title: "Trademark Opposition",
    client: "BrandSecure Inc.",
    clientId: "c21",
    status: "ACTIVE",
    practiceArea: "INTELLECTUAL_PROPERTY",
    priority: "URGENT",
    openedAt: "2024-07-18",
    nextDeadline: "2025-01-30",
    description:
      "Trademark opposition proceeding against confusingly similar mark.",
    notes: [],
  },
  {
    id: "22",
    title: "Commercial Lease Dispute",
    client: "Restaurant Owners Group",
    clientId: "c22",
    status: "CLOSED",
    practiceArea: "CIVIL_LITIGATION",
    priority: "LOW",
    openedAt: "2024-01-15",
    nextDeadline: "2024-08-01",
    description: "Breach of commercial lease agreement and rent dispute.",
    notes: [
      {
        id: "n22-1",
        content:
          "Case resolved through arbitration. Settlement payment received.",
        createdAt: "2024-08-10T15:30:00",
        author: "John Attorney",
      },
    ],
  },
  {
    id: "23",
    title: "Merger Regulatory Approval",
    client: "PharmaMerge Co.",
    clientId: "c23",
    status: "PENDING",
    practiceArea: "CORPORATE",
    priority: "HIGH",
    openedAt: "2024-10-30",
    nextDeadline: "2025-06-15",
    description:
      "Securing regulatory approvals for pharmaceutical company merger.",
    notes: [],
  },
  {
    id: "24",
    title: "Personal Injury Claim",
    client: "Susan Carter",
    clientId: "c24",
    status: "ACTIVE",
    practiceArea: "CIVIL_LITIGATION",
    priority: "HIGH",
    openedAt: "2024-09-10",
    nextDeadline: "2025-02-14",
    description: "Personal injury lawsuit following automobile accident.",
    notes: [
      {
        id: "n24-1",
        content:
          "Medical records collection in progress. Expert witness contacted.",
        createdAt: "2024-10-05T11:00:00",
        author: "John Attorney",
      },
    ],
  },
  {
    id: "25",
    title: "Artwork Authenticity Dispute",
    client: "Preston Gallery",
    clientId: "c25",
    status: "CLOSED",
    practiceArea: "CIVIL_LITIGATION",
    priority: "HIGH",
    openedAt: "2024-02-28",
    nextDeadline: "2024-09-15",
    description:
      "Dispute over authenticity and provenance of a valuable painting.",
    notes: [
      {
        id: "n25-1",
        content: "Authenticity verified by experts. Case dismissed.",
        createdAt: "2024-09-10T09:45:00",
        author: "Lisa Defense",
      },
    ],
  },
  {
    id: "26",
    title: "Software License Compliance",
    client: "Enterprise Solutions Ltd.",
    clientId: "c26",
    status: "ARCHIVED",
    practiceArea: "CORPORATE",
    priority: "LOW",
    openedAt: "2023-11-05",
    nextDeadline: "2024-05-20",
    description:
      "Compliance review and audit of enterprise software licensing agreements.",
    notes: [
      {
        id: "n26-1",
        content:
          "Compliance audit completed. All licenses verified and documented.",
        createdAt: "2024-05-15T14:10:00",
        author: "Michael IP",
      },
    ],
  },
];

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Robert Smith",
    email: "robert@smithent.com",
    phone: "(555) 123-4567",
    company: "Smith Enterprises",
    address: "123 Main St, New York, NY 10001",
    casesCount: 2,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Long-term corporate client specializing in real estate investments with multiple commercial properties.",
    notes: [
      {
        id: "note1",
        content: "Prefers email communication for case updates.",
        createdAt: "2024-10-01T09:00:00",
        author: "Attorney A",
      },
      {
        id: "note2",
        content:
          "Annual retainer agreement expires June 2024 - follow up for renewal.",
        createdAt: "2024-03-15T14:30:00",
        author: "Paralegal B",
      },
    ],
  },
  {
    id: "2",
    name: "Sarah Williams",
    email: "sarah.williams@email.com",
    phone: "(555) 234-5678",
    company: "Williams Family Trust",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    casesCount: 1,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Family trust established in 2018, managing estate planning and wealth transfer strategies.",
    notes: [
      {
        id: "note3",
        content: "Meeting scheduled for estate plan review on Nov 20.",
        createdAt: "2024-10-10T11:15:00",
        author: "Attorney C",
      },
    ],
  },
  {
    id: "12",
    name: "Jennifer Lee",
    email: "jennifer.lee@email.com",
    phone: "(555) 234-5670",
    company: "",
    address: "606 Birch Lane, Seattle, WA 98101",
    casesCount: 2,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Software engineer seeking intellectual property protection for a new mobile application.",
    notes: [
      {
        id: "note4",
        content:
          "Patent filing in progress - needs to provide additional technical specifications.",
        createdAt: "2024-09-22T16:45:00",
        author: "Attorney D",
      },
    ],
  },
  {
    id: "18",
    name: "City of Springfield",
    email: "cityattorney@springfield.gov",
    phone: "(555) 890-1235",
    company: "Springfield City Government",
    address: "1200 Government Center, Springfield, IL 62701",
    casesCount: 4,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description:
      "Municipal client handling zoning disputes, public contract law, and employment matters.",
    notes: [
      {
        id: "note5",
        content: "Pending zoning case hearing scheduled for December 5.",
        createdAt: "2024-10-05T10:00:00",
        author: "Attorney E",
      },
      {
        id: "note6",
        content: "Annual contract renewal due January 2024.",
        createdAt: "2024-09-30T15:20:00",
        author: "Paralegal F",
      },
    ],
  },
  {
    id: "3",
    name: "Davis Corporation",
    email: "legal@daviscorp.com",
    phone: "(555) 345-6789",
    company: "Davis Corporation",
    address: "789 Corporate Blvd, Chicago, IL 60601",
    casesCount: 5,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Manufacturing company with international operations, requiring cross-border legal support.",
    notes: [
      {
        id: "note7",
        content: "Merger discussions with German partner ongoing.",
        createdAt: "2024-10-12T13:00:00",
        author: "Attorney G",
      },
    ],
  },
  {
    id: "23",
    name: "Hope Foundation",
    email: "legal@hopefoundation.org",
    phone: "(555) 345-6781",
    company: "Hope Foundation International",
    address: "1700 Charity Lane, Chicago, IL 60602",
    casesCount: 2,
    status: "ACTIVE",
    type: "NON_PROFIT",
    description:
      "International humanitarian organization focused on disaster relief and community development.",
    notes: [
      {
        id: "note8",
        content: "501(c)(3) status confirmed - tax exemption documents filed.",
        createdAt: "2024-09-18T11:30:00",
        author: "Attorney H",
      },
    ],
  },
  {
    id: "4",
    name: "Michael Thompson",
    email: "michael.t@email.com",
    phone: "(555) 456-7890",
    company: "",
    address: "321 Pine St, Houston, TX 77001",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Small business owner seeking assistance with employment contract disputes.",
    notes: [
      {
        id: "note9",
        content: "Former employee settlement negotiations in progress.",
        createdAt: "2024-10-08T09:45:00",
        author: "Attorney I",
      },
    ],
  },
  {
    id: "19",
    name: "State Education Department",
    email: "legal@education.state.gov",
    phone: "(555) 901-2346",
    company: "State Education Department",
    address: "1300 Capitol Building, Albany, NY 12201",
    casesCount: 3,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description:
      "State agency handling education policy compliance and institutional legal matters.",
    notes: [
      {
        id: "note10",
        content: "Upcoming hearing on special education compliance case.",
        createdAt: "2024-10-15T14:00:00",
        author: "Attorney J",
      },
    ],
  },
  {
    id: "7",
    name: "TechVantage Solutions",
    email: "legal@techvantage.com",
    phone: "(555) 789-0123",
    company: "TechVantage Solutions Inc.",
    address: "101 Tech Park Dr, San Francisco, CA 94101",
    casesCount: 3,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "SaaS company specializing in enterprise software solutions with data privacy concerns.",
    notes: [
      {
        id: "note11",
        content: "GDPR compliance audit scheduled for Q4 2024.",
        createdAt: "2024-10-03T10:30:00",
        author: "Attorney K",
      },
    ],
  },
  {
    id: "13",
    name: "David Chen",
    email: "david.chen@email.com",
    phone: "(555) 345-6780",
    company: "",
    address: "707 Cedar Rd, Atlanta, GA 30301",
    casesCount: 1,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description:
      "Real estate investor exploring legal representation for property acquisitions.",
    notes: [
      {
        id: "note12",
        content: "Initial consultation completed - follow up in 2 weeks.",
        createdAt: "2024-10-20T16:00:00",
        author: "Attorney L",
      },
    ],
  },
  {
    id: "24",
    name: "Green Earth Alliance",
    email: "legal@greenearth.org",
    phone: "(555) 456-7892",
    company: "Green Earth Environmental Alliance",
    address: "1800 Conservation Way, Portland, OR 97202",
    casesCount: 1,
    status: "ACTIVE",
    type: "NON_PROFIT",
    description:
      "Environmental advocacy group focused on conservation and sustainability litigation.",
    notes: [
      {
        id: "note13",
        content:
          "Pending lawsuit against industrial polluter in federal court.",
        createdAt: "2024-10-07T13:45:00",
        author: "Attorney M",
      },
    ],
  },
  {
    id: "8",
    name: "Global Manufacturing Co.",
    email: "compliance@globalmfg.com",
    phone: "(555) 890-1234",
    company: "Global Manufacturing Corporation",
    address: "202 Industrial Way, Detroit, MI 48201",
    casesCount: 4,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Industrial manufacturing firm with complex supply chain and regulatory compliance needs.",
    notes: [
      {
        id: "note14",
        content: "OSHA inspection response required by November 1.",
        createdAt: "2024-10-18T09:15:00",
        author: "Attorney N",
      },
    ],
  },
  {
    id: "14",
    name: "Lisa Rodriguez",
    email: "lisa.rodriguez@email.com",
    phone: "(555) 456-7891",
    company: "",
    address: "808 Willow Way, Miami, FL 33101",
    casesCount: 0,
    status: "PROSPECT",
    type: "INDIVIDUAL",
    description:
      "Potential client seeking immigration consultation for family visa applications.",
    notes: [
      {
        id: "note15",
        content: "Initial inquiry - needs documentation review.",
        createdAt: "2024-10-22T11:00:00",
        author: "Attorney O",
      },
    ],
  },
  {
    id: "20",
    name: "County Health Services",
    email: "legal@countyhealth.gov",
    phone: "(555) 012-3457",
    company: "County Public Health Department",
    address: "1400 Health Plaza, Sacramento, CA 95814",
    casesCount: 2,
    status: "ACTIVE",
    type: "GOVERNMENT",
    description:
      "County health department managing medical malpractice and regulatory compliance cases.",
    notes: [
      {
        id: "note16",
        content: "Medicaid fraud investigation support ongoing.",
        createdAt: "2024-10-14T15:30:00",
        author: "Attorney P",
      },
    ],
  },
  {
    id: "5",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "(555) 567-8901",
    company: "",
    address: "654 Elm St, Phoenix, AZ 85001",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Personal injury case following motor vehicle accident.",
    notes: [
      {
        id: "note17",
        content: "Settlement negotiations with insurance company in progress.",
        createdAt: "2024-10-09T10:45:00",
        author: "Attorney Q",
      },
    ],
  },
  {
    id: "25",
    name: "Community Health Initiative",
    email: "legal@communityhealth.org",
    phone: "(555) 567-8903",
    company: "Community Health Initiative Inc.",
    address: "1900 Wellness Circle, Atlanta, GA 30302",
    casesCount: 3,
    status: "ACTIVE",
    type: "NON_PROFIT",
    description:
      "Healthcare nonprofit providing free clinics and medical services to underserved communities.",
    notes: [
      {
        id: "note18",
        content: "Malpractice insurance renewal due December 2024.",
        createdAt: "2024-10-16T14:15:00",
        author: "Attorney R",
      },
    ],
  },
  {
    id: "9",
    name: "James Wilson",
    email: "james@wilsonpharma.com",
    phone: "(555) 901-2345",
    company: "Wilson Pharmaceuticals",
    address: "303 Research Park, Boston, MA 02101",
    casesCount: 2,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Pharmaceutical research company with intellectual property and FDA compliance matters.",
    notes: [
      {
        id: "note19",
        content: "Patent infringement case scheduled for trial in February.",
        createdAt: "2024-10-11T13:20:00",
        author: "Attorney S",
      },
    ],
  },
  {
    id: "21",
    name: "Federal Housing Authority",
    email: "fha.legal@housing.gov",
    phone: "(555) 123-4561",
    company: "Federal Housing Authority",
    address: "1500 Federal Way, Washington, DC 20001",
    casesCount: 1,
    status: "PROSPECT",
    type: "GOVERNMENT",
    description:
      "Federal agency seeking representation for fair housing compliance and discrimination cases.",
    notes: [
      {
        id: "note20",
        content: "Proposal submitted - awaiting contract award decision.",
        createdAt: "2024-10-25T16:30:00",
        author: "Attorney T",
      },
    ],
  },
  {
    id: "15",
    name: "Thomas Anderson",
    email: "thomas.a@email.com",
    phone: "(555) 567-8902",
    company: "",
    address: "909 Spruce Ave, Denver, CO 80201",
    casesCount: 3,
    status: "INACTIVE",
    type: "INDIVIDUAL",
    description:
      "Former client with completed divorce and child custody matters.",
    notes: [
      {
        id: "note21",
        content: "Case closed as of September 2024.",
        createdAt: "2024-09-30T12:00:00",
        author: "Attorney U",
      },
    ],
  },
  {
    id: "10",
    name: "Metro Retail Group",
    email: "legal@metrorg.com",
    phone: "(555) 012-3456",
    company: "Metro Retail Group",
    address: "404 Shopping Plaza, Dallas, TX 75201",
    casesCount: 1,
    status: "INACTIVE",
    type: "CORPORATE",
    description:
      "Retail chain with completed merger and acquisition transactions.",
    notes: [
      {
        id: "note22",
        content: "Contract concluded - client acquired by larger competitor.",
        createdAt: "2024-08-15T11:00:00",
        author: "Attorney V",
      },
    ],
  },
  {
    id: "26",
    name: "Arts & Culture Council",
    email: "legal@artscouncil.org",
    phone: "(555) 678-9014",
    company: "Arts & Culture Council",
    address: "2000 Creative Plaza, New York, NY 10002",
    casesCount: 1,
    status: "PROSPECT",
    type: "NON_PROFIT",
    description:
      "Cultural organization seeking assistance with grant compliance and artist contracts.",
    notes: [
      {
        id: "note23",
        content: "Initial meeting scheduled for November 5.",
        createdAt: "2024-10-28T10:00:00",
        author: "Attorney W",
      },
    ],
  },
  {
    id: "16",
    name: "Amanda Johnson",
    email: "amanda.j@email.com",
    phone: "(555) 678-9013",
    company: "",
    address: "1010 Redwood Blvd, Portland, OR 97201",
    casesCount: 1,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description: "Employment discrimination case against former employer.",
    notes: [
      {
        id: "note24",
        content: "EEOC mediation scheduled for next month.",
        createdAt: "2024-10-17T14:45:00",
        author: "Attorney X",
      },
    ],
  },
  {
    id: "22",
    name: "Municipal Water District",
    email: "legal@waterdistrict.gov",
    phone: "(555) 234-5671",
    company: "Municipal Water & Power",
    address: "1600 Utility Center, San Diego, CA 92101",
    casesCount: 0,
    status: "INACTIVE",
    type: "GOVERNMENT",
    description:
      "Public utility with completed environmental compliance cases.",
    notes: [
      {
        id: "note25",
        content: "Contract not renewed - client moved legal services in-house.",
        createdAt: "2024-07-20T15:00:00",
        author: "Attorney Y",
      },
    ],
  },
  {
    id: "11",
    name: "Quantum Financial",
    email: "compliance@quantumfin.com",
    phone: "(555) 123-4560",
    company: "Quantum Financial Services",
    address: "505 Wall Street, New York, NY 10005",
    casesCount: 6,
    status: "ACTIVE",
    type: "CORPORATE",
    description:
      "Financial services firm with extensive SEC compliance and regulatory reporting needs.",
    notes: [
      {
        id: "note26",
        content: "SEC filing deadline approaching - intensive review required.",
        createdAt: "2024-10-13T09:30:00",
        author: "Attorney Z",
      },
      {
        id: "note27",
        content: "Quarterly compliance meeting scheduled for October 30.",
        createdAt: "2024-10-19T13:00:00",
        author: "Paralegal AA",
      },
    ],
  },
  {
    id: "17",
    name: "Brian Miller",
    email: "brian.miller@email.com",
    phone: "(555) 789-0124",
    company: "",
    address: "1111 Sequoia Dr, Austin, TX 73301",
    casesCount: 2,
    status: "ACTIVE",
    type: "INDIVIDUAL",
    description:
      "Startup founder requiring assistance with incorporation and investor agreements.",
    notes: [
      {
        id: "note28",
        content: "Series A funding round documentation in preparation.",
        createdAt: "2024-10-06T11:15:00",
        author: "Attorney AB",
      },
    ],
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2024-001",
    clientName: "Robert Smith",
    clientId: "c1",
    caseReference: "Smith vs. Johnson Corp",
    caseId: "1",
    amount: 5500,
    issueDate: "2024-11-15",
    dueDate: "2024-12-15",
    status: "paid",
    lineItems: [
      {
        id: "li1",
        description: "Initial Consultation",
        hours: 2,
        rate: 250,
        amount: 500,
      },
      {
        id: "li2",
        description: "Document Review",
        hours: 10,
        rate: 200,
        amount: 2000,
      },
      {
        id: "li3",
        description: "Court Filing Preparation",
        hours: 15,
        rate: 200,
        amount: 3000,
      },
    ],
    subtotal: 5500,
    tax: 0,
    discount: 0,
    total: 5500,
    notes: "Payment received via wire transfer.",
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2024-002",
    clientName: "Davis Corporation",
    clientId: "c3",
    caseReference: "Davis Corp Merger",
    caseId: "3",
    amount: 15000,
    issueDate: "2024-12-01",
    dueDate: "2024-12-31",
    status: "unpaid",
    lineItems: [
      {
        id: "li4",
        description: "Merger Due Diligence",
        hours: 40,
        rate: 300,
        amount: 12000,
      },
      {
        id: "li5",
        description: "Contract Drafting",
        hours: 10,
        rate: 300,
        amount: 3000,
      },
    ],
    subtotal: 15000,
    tax: 0,
    discount: 0,
    total: 15000,
    notes: "Net 30 payment terms.",
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2024-003",
    clientName: "Emily Brown",
    clientId: "c6",
    caseReference: "Brown Property Sale",
    caseId: "6",
    amount: 3500,
    issueDate: "2024-11-20",
    dueDate: "2024-12-20",
    status: "overdue",
    lineItems: [
      {
        id: "li6",
        description: "Property Title Search",
        hours: 5,
        rate: 200,
        amount: 1000,
      },
      {
        id: "li7",
        description: "Contract Review",
        hours: 10,
        rate: 200,
        amount: 2000,
      },
      {
        id: "li8",
        description: "Closing Preparation",
        hours: 2.5,
        rate: 200,
        amount: 500,
      },
    ],
    subtotal: 3500,
    tax: 0,
    discount: 0,
    total: 3500,
    notes: "Follow up required for payment.",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "Complaint_Filed.pdf",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    uploadDate: "2024-08-20",
    size: "2.4 MB",
    type: "Legal Filing",
    description: "",
  },
  {
    id: "d2",
    name: "Contract_Exhibit_A.pdf",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    uploadDate: "2024-08-22",
    size: "1.2 MB",
    type: "Evidence",
    description: "",
  },
  {
    id: "d3",
    name: "Will_Draft_v2.docx",
    caseId: "2",
    caseName: "Estate of Williams",
    uploadDate: "2024-09-05",
    size: "456 KB",
    type: "Draft",
    description: "",
  },
  {
    id: "d4",
    name: "Merger_Agreement.pdf",
    caseId: "3",
    caseName: "Davis Corp Merger",
    uploadDate: "2024-07-15",
    size: "5.8 MB",
    type: "Contract",
    description: "",
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    caseId: "1",
    date: "2024-12-10",
    type: "meeting",
    summary: "Strategy discussion with client regarding settlement options",
    duration: "1.5 hours",
  },
  {
    id: "m2",
    caseId: "1",
    date: "2024-12-05",
    type: "call",
    summary: "Phone call with opposing counsel",
    duration: "30 mins",
  },
  {
    id: "m3",
    caseId: "3",
    date: "2024-12-08",
    type: "meeting",
    summary: "Board presentation on merger terms",
    duration: "2 hours",
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Draft settlement agreement",
    caseId: "6",
    caseName: "Brown Property Sale",
    assignee: "Alexandra Mitchell",
    dueDate: "2025-02-08",
    completed: false,
    priority: "high",
  },
  {
    id: "t2",
    title: "Review discovery documents",
    caseId: "1",
    caseName: "Smith vs. Johnson Corp",
    assignee: "Alexandra Mitchell",
    dueDate: "2025-02-07",
    completed: false,
    priority: "high",
  },
  {
    id: "t3",
    title: "Prepare immigration forms",
    caseId: "5",
    caseName: "Garcia Immigration",
    assignee: "Alexandra Mitchell",
    dueDate: "2025-02-10",
    completed: false,
    priority: "medium",
  },
  {
    id: "t4",
    title: "Client meeting prep",
    caseId: "3",
    caseName: "Davis Corp Merger",
    assignee: "Alexandra Mitchell",
    dueDate: "2025-02-09",
    completed: false,
    priority: "medium",
  },
  {
    id: "t5",
    title: "File court response",
    caseId: "8",
    caseName: "Anderson Liability",
    assignee: "Alexandra Mitchell",
    dueDate: "2025-02-06",
    completed: false,
    priority: "high",
  },
];

export const mockSchedule: ScheduledMeeting[] = [
  {
    id: "ms1",
    title: "Client Call - Robert Smith",
    time: "10:00 AM",
    duration: "30 min",
    type: "call",
    hasVideoLink: true,
  },
  {
    id: "ms2",
    title: "Deposition Prep - Anderson",
    time: "2:00 PM",
    duration: "1 hour",
    type: "meeting",
    hasVideoLink: false,
  },
  {
    id: "ms3",
    title: "Court Hearing - Smith",
    time: "3:30 PM",
    duration: "2 hours",
    type: "hearing",
    hasVideoLink: false,
  },
];

export const mockCommunications: Communication[] = [
  {
    id: "cm1",
    clientName: "Robert Smith",
    clientId: "c1",
    type: "email",
    subject: "Re: Settlement offer review",
    time: "30 min ago",
    unread: true,
  },
  {
    id: "cm2",
    clientName: "Davis Corporation",
    clientId: "c3",
    type: "call",
    subject: "Merger timeline discussion",
    time: "2 hours ago",
    unread: true,
  },
  {
    id: "cm3",
    clientName: "Maria Garcia",
    clientId: "c5",
    type: "email",
    subject: "Visa application update",
    time: "Yesterday",
    unread: false,
  },
  {
    id: "cm4",
    clientName: "Emily Brown",
    clientId: "c6",
    type: "message",
    subject: "Closing date confirmation",
    time: "Yesterday",
    unread: false,
  },
];

// Chart data
export const revenueData = [
  { month: "Jul", revenue: 42000 },
  { month: "Aug", revenue: 38000 },
  { month: "Sep", revenue: 52000 },
  { month: "Oct", revenue: 48000 },
  { month: "Nov", revenue: 55000 },
  { month: "Dec", revenue: 48250 },
];

export const casesByPracticeArea = [
  { area: "Civil Litigation", count: 8, fill: "hsl(210, 100%, 63%)" },
  { area: "Estate Planning", count: 5, fill: "hsl(145, 63%, 49%)" },
  { area: "Corporate Law", count: 6, fill: "hsl(35, 91%, 62%)" },
  { area: "Family Law", count: 4, fill: "hsl(0, 86%, 69%)" },
  { area: "Real Estate", count: 5, fill: "hsl(270, 60%, 60%)" },
];

export const caseStatusData = [
  { name: "Active", value: 12, fill: "hsl(210, 100%, 63%)" },
  { name: "Pending", value: 6, fill: "hsl(35, 91%, 62%)" },
  { name: "Closed", value: 6, fill: "hsl(145, 63%, 49%)" },
];

export const upcomingDeadlines = [
  {
    id: "1",
    task: "Motion Response",
    case: "Smith vs. Johnson Corp",
    caseId: "1",
    dueDate: "2024-12-23",
    daysUntil: 0,
  },
  {
    id: "2",
    task: "Document Filing",
    case: "Estate of Williams",
    caseId: "2",
    dueDate: "2024-12-24",
    daysUntil: 1,
  },
  {
    id: "3",
    task: "Discovery Deadline",
    case: "Davis Corp Merger",
    caseId: "3",
    dueDate: "2024-12-28",
    daysUntil: 5,
  },
  {
    id: "4",
    task: "Court Hearing",
    case: "Garcia Immigration",
    caseId: "5",
    dueDate: "2025-01-05",
    daysUntil: 13,
  },
];
